export type SaintstreamTitle = {
  id: string
  titleEn: string
  titleFa: string
  poster: string
  backdrop: string
  year: number
  rating: number
  maturity: string
  duration: string
  genres: string[]
  description: string
  type: 'Film' | 'Series'
  rank?: number
  live?: boolean
}

export type SaintstreamHome = {
  heroSlides: SaintstreamTitle[]
  justRelease: SaintstreamTitle[]
  popularWeek: SaintstreamTitle[]
  featured: SaintstreamTitle
  featuredSide: SaintstreamTitle[]
  movies: SaintstreamTitle[]
  series: SaintstreamTitle[]
  koreanSeries: SaintstreamTitle[]
  award: SaintstreamTitle
  popularList: SaintstreamTitle[]
  liveList: SaintstreamTitle[]
}

const p = (name: string) => `/saintstream/posters/${name}.webp`
const h = (name: string) => `/saintstream/hero/${name}.webp`

/** Catalog mirrors Saintstream Figma Home — HQ posters/backdrops from web */
const titles: Record<string, SaintstreamTitle> = {
  'star-wars-tfa': {
    id: 'star-wars-tfa',
    titleEn: 'Star Wars: The Force Awakens',
    titleFa: 'Star Wars: The Force Awakens',
    poster: p('star-wars-tfa'),
    backdrop: h('star-wars-backdrop'),
    year: 2015,
    rating: 4.8,
    maturity: 'PG-13',
    duration: '۲س ۱۳د',
    genres: ['فانتزی', 'اکشن'],
    description:
      'ری با در کنار جنگجویان مقاومت برای یافتن لوک اسکای‌واکر گم‌شده به کهکشان سفر می‌کند. در این میان نیروی تاریک سوم در حال ظهور است.',
    type: 'Film',
  },
  'dune-part-two': {
    id: 'dune-part-two',
    titleEn: 'Dune: Part Two',
    titleFa: 'Dune: Part Two',
    poster: p('dune-part-two'),
    backdrop: h('dune-part-two'),
    year: 2024,
    rating: 4.7,
    maturity: 'PG-13',
    duration: '۲س ۴۶د',
    genres: ['علمی-تخیلی', 'ماجراجویی'],
    description:
      'پاول آترییدس با چانی و فرمن‌ها برای انتقام از توطئه‌گرانی که خانواده‌اش را نابود کردند متحد می‌شود.',
    type: 'Film',
  },
  'enola-holmes-2': {
    id: 'enola-holmes-2',
    titleEn: 'Enola Holmes 2',
    titleFa: 'Enola Holmes 2',
    poster: p('enola-holmes-2'),
    backdrop: p('enola-holmes-2'),
    year: 2022,
    rating: 3.7,
    maturity: 'PG-13',
    duration: '۱س ۵۹د',
    genres: ['معمایی', 'ماجراجویی'],
    description:
      'انولا در لندن ویکتوریایی به‌عنوان کارآگاه خصوصی پروندهٔ ناپدید شدن یک دختر کارگر را بر عهده می‌گیرد.',
    type: 'Film',
  },
  'satans-slaves': {
    id: 'satans-slaves',
    titleEn: "Satan's Slaves",
    titleFa: "Satan's Slaves",
    poster: p('satans-slaves'),
    backdrop: p('satans-slaves'),
    year: 2017,
    rating: 4.1,
    maturity: 'R',
    duration: '۱س ۴۷د',
    genres: ['ترسناک', 'درام'],
    description: 'پس از مرگ مادر، خانواده‌ای در جاوه با روح‌های تاریک خانه قدیمی‌شان روبه‌رو می‌شوند.',
    type: 'Film',
  },
  'the-flash': {
    id: 'the-flash',
    titleEn: 'The Flash',
    titleFa: 'The Flash',
    poster: p('the-flash'),
    backdrop: p('the-flash'),
    year: 2023,
    rating: 3.9,
    maturity: 'PG-13',
    duration: '۱س ۴۴د',
    genres: ['اکشن', 'علمی-تخیلی'],
    description: 'بری آلن با سفر در زمان سعی می‌کند گذشته را تغییر دهد اما جهان چندگانه را به خطر می‌اندازد.',
    type: 'Film',
  },
  'weak-hero': {
    id: 'weak-hero',
    titleEn: 'Weak Hero Class 1',
    titleFa: 'Weak Hero Class 1',
    poster: p('weak-hero'),
    backdrop: p('weak-hero'),
    year: 2022,
    rating: 4.4,
    maturity: 'TV-14',
    duration: 'سریال',
    genres: ['اکشن', 'درام'],
    description: 'دانش‌آموزی باهوش برای بقا در مدرسه‌ای پر از خشونت می‌جنگد.',
    type: 'Series',
  },
  ghosted: {
    id: 'ghosted',
    titleEn: 'Ghosted',
    titleFa: 'Ghosted',
    poster: p('ghosted'),
    backdrop: p('ghosted'),
    year: 2023,
    rating: 2.9,
    maturity: 'PG-13',
    duration: '۱س ۵۷د',
    genres: ['اکشن', 'عاشقانه'],
    description: 'کول یک کشاورز معمولی برای نجات معشوقش که جاسوس است به ماموریتی پرخطر می‌رود.',
    type: 'Film',
  },
  'black-clover': {
    id: 'black-clover',
    titleEn: 'Black Clover: Sword of the Wizard King',
    titleFa: 'Black Clover: Sword of the Wizard King',
    poster: p('black-clover'),
    backdrop: p('black-clover'),
    year: 2023,
    rating: 4.0,
    maturity: 'PG-13',
    duration: '۱س ۵۳د',
    genres: ['فانتزی', 'اکشن'],
    description: 'آستا و یونو برای محافظت از پادشاهی کلاور در برابر تهدید پادشاه جادوگر می‌جنگند.',
    type: 'Film',
  },
  'the-last-of-us': {
    id: 'the-last-of-us',
    titleEn: 'The Last of Us',
    titleFa: 'The Last of Us',
    poster: p('the-last-of-us'),
    backdrop: h('the-last-of-us'),
    year: 2023,
    rating: 4.9,
    maturity: 'TV-MA',
    duration: 'سریال',
    genres: ['درام', 'ترسناک'],
    description: 'جوئل و الی در آمریکا پس از آخرالزمان برای بقا سفر می‌کنند.',
    type: 'Series',
  },
  'sri-asih': {
    id: 'sri-asih',
    titleEn: 'Sri Asih',
    titleFa: 'Sri Asih',
    poster: p('sri-asih'),
    backdrop: p('sri-asih'),
    year: 2022,
    rating: 4.2,
    maturity: 'PG-13',
    duration: '۱س ۵۹د',
    genres: ['اکشن', 'فانتزی'],
    description: 'آلانا کشف می‌کند که سری آسیه، قهرمان افسانه‌ای اندونزی، در درون او زنده است.',
    type: 'Film',
  },
  air: {
    id: 'air',
    titleEn: 'Air',
    titleFa: 'Air',
    poster: p('air'),
    backdrop: h('air-featured'),
    year: 2023,
    rating: 4.5,
    maturity: 'R',
    duration: '۱س ۵۱د',
    genres: ['درام', 'ورزشی'],
    description: 'تیم نایکی در دهه ۸۰ برای امضای قرارداد با مایکل جردن تلاش می‌کند و ایر جردن متولد می‌شود.',
    type: 'Film',
  },
  gundala: {
    id: 'gundala',
    titleEn: 'Gundala',
    titleFa: 'Gundala',
    poster: p('gundala'),
    backdrop: p('gundala'),
    year: 2019,
    rating: 4.3,
    maturity: 'PG-13',
    duration: '۲س ۳د',
    genres: ['اکشن', 'فانتزی'],
    description: 'سانکاکا قدرت‌های الکترومغناطیسی را کشف می‌کند و به قهرمان گوندالا تبدیل می‌شود.',
    type: 'Film',
  },
  oppenheimer: {
    id: 'oppenheimer',
    titleEn: 'Oppenheimer',
    titleFa: 'Oppenheimer',
    poster: p('oppenheimer'),
    backdrop: h('oppenheimer'),
    year: 2023,
    rating: 4.8,
    maturity: 'R',
    duration: '۳س',
    genres: ['درام', 'تاریخی'],
    description: 'داستان فیزیکدان رابرت اوپنهایمر و پروژه منهتن.',
    type: 'Film',
  },
  'sonic-2': {
    id: 'sonic-2',
    titleEn: 'Sonic the Hedgehog 2',
    titleFa: 'Sonic the Hedgehog 2',
    poster: p('sonic-2'),
    backdrop: p('sonic-2'),
    year: 2022,
    rating: 4.0,
    maturity: 'PG',
    duration: '۱س ۵۲د',
    genres: ['اکشن', 'ماجراجویی'],
    description: 'سونیک و تیلز برای مقابله با ناکلز و دکتر رباتنیک متحد می‌شوند.',
    type: 'Film',
    live: true,
  },
  pathaan: {
    id: 'pathaan',
    titleEn: 'Pathaan',
    titleFa: 'Pathaan',
    poster: p('pathaan'),
    backdrop: p('pathaan'),
    year: 2023,
    rating: 4.1,
    maturity: 'PG-13',
    duration: '۲س ۲۶د',
    genres: ['اکشن', 'هیجان'],
    description: 'پاتان مأمور راو برای جلوگیری از حمله سلاح بیولوژیک به هند مأموریت می‌گیرد.',
    type: 'Film',
    live: true,
  },
  'squid-game': {
    id: 'squid-game',
    titleEn: 'Squid Game',
    titleFa: 'Squid Game',
    poster: p('squid-game'),
    backdrop: h('squid-game'),
    year: 2021,
    rating: 4.6,
    maturity: 'TV-MA',
    duration: 'سریال',
    genres: ['هیجان', 'درام'],
    description: 'بازیکنان در بازی‌های مرگبار کودکی برای جایزه میلیاردی شرکت می‌کنند.',
    type: 'Series',
  },
  wednesday: {
    id: 'wednesday',
    titleEn: 'Wednesday',
    titleFa: 'Wednesday',
    poster: p('wednesday'),
    backdrop: p('wednesday'),
    year: 2022,
    rating: 4.5,
    maturity: 'TV-14',
    duration: 'سریال',
    genres: ['کمدی', 'ترسناک'],
    description: 'ونزدی آدامز در مدرسهٔ نِورمورت با قدرت‌هایش رازهای تاریک را کشف می‌کند.',
    type: 'Series',
  },
  beef: {
    id: 'beef',
    titleEn: 'Beef',
    titleFa: 'Beef',
    poster: p('beef'),
    backdrop: p('beef'),
    year: 2023,
    rating: 4.6,
    maturity: 'TV-MA',
    duration: 'سریال',
    genres: ['کمدی', 'درام'],
    description: 'یک جروبحث رانندگی زندگی دو غریبه را به مارپیچی از انتقام می‌کشاند.',
    type: 'Series',
  },
  witcher: {
    id: 'witcher',
    titleEn: 'The Witcher',
    titleFa: 'The Witcher',
    poster: p('witcher'),
    backdrop: p('witcher'),
    year: 2019,
    rating: 4.2,
    maturity: 'TV-MA',
    duration: 'سریال',
    genres: ['فانتزی', 'اکشن'],
    description: 'گرالت از ریویا، شکارچی هیولا، در جهانی پر از جادو و سیاست سرنوشتش را دنبال می‌کند.',
    type: 'Series',
  },
  'valhalla-murders': {
    id: 'valhalla-murders',
    titleEn: 'The Valhalla Murders',
    titleFa: 'The Valhalla Murders',
    poster: p('valhalla-murders'),
    backdrop: p('valhalla-murders'),
    year: 2019,
    rating: 4.1,
    maturity: 'TV-MA',
    duration: 'سریال',
    genres: ['جنایی', 'معمایی'],
    description:
      'کارآگاهی از اسلو به ایسلند بازمی‌گردد تا در شکار قاتلی زنجیره‌ای با پیوند به گذشته‌ای تاریک کمک کند.',
    type: 'Series',
  },
  mechamato: {
    id: 'mechamato',
    titleEn: 'Mechamato Movie',
    titleFa: 'Mechamato Movie',
    poster: p('mechamato'),
    backdrop: p('mechamato'),
    year: 2022,
    rating: 4.0,
    maturity: 'PG',
    duration: '۲س ۲د',
    genres: ['انیمیشن', 'ماجراجویی'],
    description: 'آماتو با مکابات روبه‌رو می‌شود و برای مقابله با شکارچی قدرت‌های فضایی متحد می‌شوند.',
    type: 'Film',
  },
  toxic: {
    id: 'toxic',
    titleEn: 'Toxic',
    titleFa: 'Toxic',
    poster: p('toxic'),
    backdrop: p('toxic'),
    year: 2022,
    rating: 4.0,
    maturity: 'TV-14',
    duration: '۱س ۴۸د',
    genres: ['درام', 'هیجان'],
    description: 'پزشکی پس از مرگ مرموز خانواده‌اش راز فاجعهٔ ضدعفونی‌کنندهٔ مرطوب‌کننده را برملا می‌کند.',
    type: 'Film',
  },
  insider: {
    id: 'insider',
    titleEn: 'Insider',
    titleFa: 'Insider',
    poster: p('insider'),
    backdrop: p('insider'),
    year: 2022,
    rating: 4.3,
    maturity: 'TV-14',
    duration: 'سریال',
    genres: ['جنایی', 'درام'],
    description: 'کارآموز قضایی در مأموریت مخفی به زندان می‌رود تا زنده بماند و انتقام بگیرد.',
    type: 'Series',
  },
  race: {
    id: 'race',
    titleEn: 'Race',
    titleFa: 'Race',
    poster: p('race'),
    backdrop: p('race'),
    year: 2023,
    rating: 4.0,
    maturity: 'TV-14',
    duration: 'سریال',
    genres: ['درام', 'عاشقانه'],
    description: 'زن جوان با شور و اشتیاق وارد شرکت بزرگ می‌شود و در رقابت کاری و زندگی پیش می‌رود.',
    type: 'Series',
  },
  'ghost-doctor': {
    id: 'ghost-doctor',
    titleEn: 'Ghost Doctor',
    titleFa: 'Ghost Doctor',
    poster: p('ghost-doctor'),
    backdrop: p('ghost-doctor'),
    year: 2022,
    rating: 4.4,
    maturity: 'TV-14',
    duration: 'سریال',
    genres: ['کمدی', 'فانتزی'],
    description: 'جراح نابغه پس از حادثه روحش بدن رزیدنت تازه‌کار را تسخیر می‌کند.',
    type: 'Series',
  },
  fall: {
    id: 'fall',
    titleEn: 'Fall',
    titleFa: 'Fall',
    poster: p('fall'),
    backdrop: p('fall'),
    year: 2022,
    rating: 4.2,
    maturity: 'PG-13',
    duration: '۱س ۴۷د',
    genres: ['هیجان', 'ماجراجویی'],
    description: 'دو دوست روی برج مخابراتی گیر می‌افتند و برای بقا می‌جنگند.',
    type: 'Film',
  },
  'extraordinary-attorney-woo': {
    id: 'extraordinary-attorney-woo',
    titleEn: 'Extraordinary Attorney Woo',
    titleFa: 'Extraordinary Attorney Woo',
    poster: p('extraordinary-attorney-woo'),
    backdrop: p('extraordinary-attorney-woo'),
    year: 2022,
    rating: 4.7,
    maturity: 'TV-14',
    duration: 'سریال',
    genres: ['درام', 'کمدی'],
    description: 'وکیل جوان با اوتیسم در یک مؤسسه بزرگ حقوقی پرونده‌های پیچیده را حل می‌کند.',
    type: 'Series',
  },
  'kingdom-ashin': {
    id: 'kingdom-ashin',
    titleEn: 'Kingdom: Ashin of the North',
    titleFa: 'Kingdom: Ashin of the North',
    poster: p('kingdom-ashin'),
    backdrop: p('kingdom-ashin'),
    year: 2021,
    rating: 4.4,
    maturity: 'TV-MA',
    duration: '۱س ۳۲د',
    genres: ['ترسناک', 'تاریخی'],
    description: 'پیش‌درآمد کینگدام درباره آشین و ریشه‌های طاعون زامبی.',
    type: 'Film',
  },
  'ant-man-quantumania': {
    id: 'ant-man-quantumania',
    titleEn: 'Ant-Man and the Wasp: Quantumania',
    titleFa: 'Ant-Man and the Wasp: Quantumania',
    poster: p('ant-man-quantumania'),
    backdrop: p('ant-man-quantumania'),
    year: 2023,
    rating: 3.8,
    maturity: 'PG-13',
    duration: '۲س ۵د',
    genres: ['اکشن', 'ماجراجویی'],
    description: 'اسکات لنگ و خانواده‌اش به قلمرو کوانتومی می‌روند و با کانگ روبه‌رو می‌شوند.',
    type: 'Film',
  },
  'john-wick-4': {
    id: 'john-wick-4',
    titleEn: 'John Wick: Chapter 4',
    titleFa: 'John Wick: Chapter 4',
    poster: p('john-wick-4'),
    backdrop: h('john-wick-4'),
    year: 2023,
    rating: 4.6,
    maturity: 'R',
    duration: '۲س ۴۹د',
    genres: ['اکشن', 'هیجان'],
    description: 'جان ویک برای آزادی از High Table با دشمنان قدرتمند در جهان می‌جنگد.',
    type: 'Film',
  },
  'black-adam': {
    id: 'black-adam',
    titleEn: 'Black Adam',
    titleFa: 'Black Adam',
    poster: p('black-adam'),
    backdrop: p('black-adam'),
    year: 2022,
    rating: 3.7,
    maturity: 'PG-13',
    duration: '۲س ۵د',
    genres: ['اکشن', 'فانتزی'],
    description: 'پس از ۵۰۰۰ سال، بلک آدم آزاد می‌شود و قدرتش جهان مدرن را تهدید می‌کند.',
    type: 'Film',
    live: true,
  },
  interstellar: {
    id: 'interstellar',
    titleEn: 'Interstellar',
    titleFa: 'Interstellar',
    poster: p('interstellar'),
    backdrop: h('interstellar'),
    year: 2014,
    rating: 4.9,
    maturity: 'PG-13',
    duration: '۲س ۴۹د',
    genres: ['علمی-تخیلی', 'درام'],
    description:
      'گروهی از کاشفان از کرم‌چاله‌ای نزدیک زمین عبور می‌کنند تا بقای بشر را در سیاره‌ای دیگر تضمین کنند.',
    type: 'Film',
  },
  inception: {
    id: 'inception',
    titleEn: 'Inception',
    titleFa: 'Inception',
    poster: p('inception'),
    backdrop: h('inception'),
    year: 2010,
    rating: 4.8,
    maturity: 'PG-13',
    duration: '۲س ۲۸د',
    genres: ['علمی-تخیلی', 'هیجان'],
    description:
      'دزدی که وارد رؤیاهای دیگران می‌شود مأموریت نفوذ به ضمیر ناخودآگاه را برای کاشتن یک ایده می‌پذیرد.',
    type: 'Film',
  },
  'the-batman': {
    id: 'the-batman',
    titleEn: 'The Batman',
    titleFa: 'The Batman',
    poster: p('the-batman'),
    backdrop: h('the-batman'),
    year: 2022,
    rating: 4.5,
    maturity: 'PG-13',
    duration: '۲س ۵۶د',
    genres: ['جنایی', 'اکشن'],
    description:
      'بتمن در سال دوم فعالیتش با معماهای سریال‌قتل‌های ریدلر و فساد گاتهام روبه‌رو می‌شود.',
    type: 'Film',
  },
  'spider-verse': {
    id: 'spider-verse',
    titleEn: 'Spider-Man: Across the Spider-Verse',
    titleFa: 'Spider-Man: Across the Spider-Verse',
    poster: p('spider-verse'),
    backdrop: h('spider-verse'),
    year: 2023,
    rating: 4.8,
    maturity: 'PG',
    duration: '۲س ۲۰د',
    genres: ['انیمیشن', 'اکشن'],
    description:
      'مایلز مورالس با جامعه‌ای از مردان عنکبوتی در میان جهان‌های موازی سفر می‌کند و انتخاب دشواری پیش رو دارد.',
    type: 'Film',
  },
  'top-gun-maverick': {
    id: 'top-gun-maverick',
    titleEn: 'Top Gun: Maverick',
    titleFa: 'Top Gun: Maverick',
    poster: p('top-gun-maverick'),
    backdrop: h('top-gun-maverick'),
    year: 2022,
    rating: 4.7,
    maturity: 'PG-13',
    duration: '۲س ۱۱د',
    genres: ['اکشن', 'درام'],
    description:
      'پس از بیش از سی سال خدمت، پیت ماوریک به مدرسهٔ تاپ گان بازمی‌گردد تا نسل جدید خلبانان را آموزش دهد.',
    type: 'Film',
  },
  'everything-everywhere': {
    id: 'everything-everywhere',
    titleEn: 'Everything Everywhere All at Once',
    titleFa: 'Everything Everywhere All at Once',
    poster: p('everything-everywhere'),
    backdrop: p('everything-everywhere'),
    year: 2022,
    rating: 4.7,
    maturity: 'R',
    duration: '۲س ۱۹د',
    genres: ['کمدی', 'علمی-تخیلی'],
    description:
      'یک زن میانسال صاحب لاندری باید نسخه‌های بی‌شمار خود را در جهان‌های موازی نجات دهد.',
    type: 'Film',
  },
  parasite: {
    id: 'parasite',
    titleEn: 'Parasite',
    titleFa: 'Parasite',
    poster: p('parasite'),
    backdrop: h('parasite'),
    year: 2019,
    rating: 4.9,
    maturity: 'R',
    duration: '۲س ۱۲د',
    genres: ['درام', 'هیجان'],
    description:
      'خانواده‌ای فقیر با نفوذ تدریجی به خانهٔ ثروتمندان، تعادل شکننده‌ای می‌سازند که به‌سرعت از هم می‌پاشد.',
    type: 'Film',
  },
  'avatar-way-of-water': {
    id: 'avatar-way-of-water',
    titleEn: 'Avatar: The Way of Water',
    titleFa: 'Avatar: The Way of Water',
    poster: p('avatar-way-of-water'),
    backdrop: h('avatar-way-of-water'),
    year: 2022,
    rating: 4.5,
    maturity: 'PG-13',
    duration: '۳س ۱۲د',
    genres: ['علمی-تخیلی', 'ماجراجویی'],
    description:
      'جیک سولی و خانواده‌اش در میان قبایل دریایی پاندورا پناه می‌گیرند تا از تهدید جدید انسان‌ها در امان بمانند.',
    type: 'Film',
  },
  'guardians-3': {
    id: 'guardians-3',
    titleEn: 'Guardians of the Galaxy Vol. 3',
    titleFa: 'Guardians of the Galaxy Vol. 3',
    poster: p('guardians-3'),
    backdrop: p('guardians-3'),
    year: 2023,
    rating: 4.6,
    maturity: 'PG-13',
    duration: '۲س ۳۰د',
    genres: ['اکشن', 'کمدی'],
    description:
      'نگهبانان برای نجات راکت باید با گذشتهٔ تاریک او و دشمن خطرناک های‌اوول‌شنری روبه‌رو شوند.',
    type: 'Film',
  },
  'stranger-things': {
    id: 'stranger-things',
    titleEn: 'Stranger Things',
    titleFa: 'Stranger Things',
    poster: p('stranger-things'),
    backdrop: h('stranger-things'),
    year: 2016,
    rating: 4.7,
    maturity: 'TV-14',
    duration: 'سریال',
    genres: ['علمی-تخیلی', 'ترسناک'],
    description:
      'در هاوکینز دههٔ ۸۰، ناپدید شدن یک پسر پرده از آزمایش‌های سری و دنیای وارونه برمی‌دارد.',
    type: 'Series',
  },
  'breaking-bad': {
    id: 'breaking-bad',
    titleEn: 'Breaking Bad',
    titleFa: 'Breaking Bad',
    poster: p('breaking-bad'),
    backdrop: h('breaking-bad'),
    year: 2008,
    rating: 4.9,
    maturity: 'TV-MA',
    duration: 'سریال',
    genres: ['جنایی', 'درام'],
    description:
      'معلم شیمی مبتلا به سرطان برای تأمین آیندهٔ خانواده‌اش وارد تولید و فروش متامفتامین می‌شود.',
    type: 'Series',
  },
  dark: {
    id: 'dark',
    titleEn: 'Dark',
    titleFa: 'Dark',
    poster: p('dark'),
    backdrop: p('dark'),
    year: 2017,
    rating: 4.8,
    maturity: 'TV-MA',
    duration: 'سریال',
    genres: ['علمی-تخیلی', 'معمایی'],
    description:
      'ناپدید شدن کودکان در شهر ویندن راز سفر در زمان و پیوند خانواده‌ها در دهه‌های مختلف را آشکار می‌کند.',
    type: 'Series',
  },
  'the-boys': {
    id: 'the-boys',
    titleEn: 'The Boys',
    titleFa: 'The Boys',
    poster: p('the-boys'),
    backdrop: h('the-boys'),
    year: 2019,
    rating: 4.6,
    maturity: 'TV-MA',
    duration: 'سریال',
    genres: ['اکشن', 'کمدی سیاه'],
    description:
      'گروهی از افراد عادی علیه سوپرهیروهای فاسد تحت کنترل شرکت ووت می‌جنگند.',
    type: 'Series',
  },
  shogun: {
    id: 'shogun',
    titleEn: 'Shōgun',
    titleFa: 'Shōgun',
    poster: p('shogun'),
    backdrop: h('shogun'),
    year: 2024,
    rating: 4.8,
    maturity: 'TV-MA',
    duration: 'سریال',
    genres: ['درام', 'تاریخی'],
    description:
      'یک دریانورد انگلیسی در ژاپن فئودال گیر می‌افتد و وارد بازی قدرت میان اربابان جنگ می‌شود.',
    type: 'Series',
  },
  arcane: {
    id: 'arcane',
    titleEn: 'Arcane',
    titleFa: 'Arcane',
    poster: p('arcane'),
    backdrop: h('arcane'),
    year: 2021,
    rating: 4.9,
    maturity: 'TV-14',
    duration: 'سریال',
    genres: ['انیمیشن', 'اکشن'],
    description:
      'داستان خواهران وای و جینکس در میان شکاف اجتماعی پیل‌توور و زون، پیش از رویدادهای League of Legends.',
    type: 'Series',
  },
  'mad-max-fury-road': {
    id: 'mad-max-fury-road',
    titleEn: 'Mad Max: Fury Road',
    titleFa: 'Mad Max: Fury Road',
    poster: p('mad-max-fury-road'),
    backdrop: p('mad-max-fury-road'),
    year: 2015,
    rating: 4.8,
    maturity: 'R',
    duration: '۲س',
    genres: ['اکشن', 'ماجراجویی'],
    description: 'مکس و فورiosa در بیابان پساآخرالزمانی از چنگ ایمورتان جو فرار می‌کنند.',
    type: 'Film',
  },
  'spider-verse-into': {
    id: 'spider-verse-into',
    titleEn: 'Spider-Man: Into the Spider-Verse',
    titleFa: 'Spider-Man: Into the Spider-Verse',
    poster: p('spider-verse-into'),
    backdrop: p('spider-verse-into'),
    year: 2018,
    rating: 4.8,
    maturity: 'PG',
    duration: '۱س ۵۷د',
    genres: ['انیمیشن', 'اکشن'],
    description: 'مایلز مورالس با عنکبوتی‌های جهان‌های دیگر متحد می‌شود تا شهر را نجات دهد.',
    type: 'Film',
  },
  gladiator: {
    id: 'gladiator',
    titleEn: 'Gladiator',
    titleFa: 'Gladiator',
    poster: p('gladiator'),
    backdrop: p('gladiator'),
    year: 2000,
    rating: 4.8,
    maturity: 'R',
    duration: '۲س ۳۵د',
    genres: ['تاریخی', 'اکشن'],
    description: 'ژنرال رومی پس از خیانت امپراتور، در عرصه برای انتقام می‌جنگد.',
    type: 'Film',
  },
  'the-conjuring': {
    id: 'the-conjuring',
    titleEn: 'The Conjuring',
    titleFa: 'The Conjuring',
    poster: p('the-conjuring'),
    backdrop: p('the-conjuring'),
    year: 2013,
    rating: 4.4,
    maturity: 'R',
    duration: '۱س ۵۲د',
    genres: ['ترسناک'],
    description: 'اد و لورین وارن به خانواده‌ای کمک می‌کنند که خانه‌شان تسخیر شده است.',
    type: 'Film',
  },
  'the-godfather': {
    id: 'the-godfather',
    titleEn: 'The Godfather',
    titleFa: 'The Godfather',
    poster: p('the-godfather'),
    backdrop: p('the-godfather'),
    year: 1972,
    rating: 4.9,
    maturity: 'R',
    duration: '۲س ۵۵د',
    genres: ['جنایی', 'درام'],
    description: 'مایکل کورلئونه ناخواسته وارث امپراتوری مافیایی پدرش می‌شود.',
    type: 'Film',
  },
  'saving-private-ryan': {
    id: 'saving-private-ryan',
    titleEn: 'Saving Private Ryan',
    titleFa: 'Saving Private Ryan',
    poster: p('saving-private-ryan'),
    backdrop: p('saving-private-ryan'),
    year: 1998,
    rating: 4.8,
    maturity: 'R',
    duration: '۲س ۴۹د',
    genres: ['جنگی', 'درام'],
    description: 'گروهی از سربازان پس از نرماندی مأمور یافتن سرباز رایان می‌شوند.',
    type: 'Film',
  },
  'home-alone': {
    id: 'home-alone',
    titleEn: 'Home Alone',
    titleFa: 'Home Alone',
    poster: p('home-alone'),
    backdrop: p('home-alone'),
    year: 1990,
    rating: 4.4,
    maturity: 'PG',
    duration: '۱س ۴۳د',
    genres: ['خانوادگی', 'کمدی'],
    description: 'کوین که در خانه جا مانده، با تله از دزدها محافظت می‌کند.',
    type: 'Film',
  },
  'shawshank-redemption': {
    id: 'shawshank-redemption',
    titleEn: 'The Shawshank Redemption',
    titleFa: 'The Shawshank Redemption',
    poster: p('shawshank-redemption'),
    backdrop: p('shawshank-redemption'),
    year: 1994,
    rating: 4.9,
    maturity: 'R',
    duration: '۲س ۲۲د',
    genres: ['درام'],
    description: 'اندی دوفرین در زندان شاوشنک امید و دوستی را زنده نگه می‌دارد.',
    type: 'Film',
  },
  'blade-runner-2049': {
    id: 'blade-runner-2049',
    titleEn: 'Blade Runner 2049',
    titleFa: 'Blade Runner 2049',
    poster: p('blade-runner-2049'),
    backdrop: p('blade-runner-2049'),
    year: 2017,
    rating: 4.6,
    maturity: 'R',
    duration: '۲س ۴۴د',
    genres: ['سایبرپانک', 'علمی‌تخیلی'],
    description: 'افسر کی رازی را کشف می‌کند که می‌تواند جامعه را از هم بپاشد.',
    type: 'Film',
  },
  titanic: {
    id: 'titanic',
    titleEn: 'Titanic',
    titleFa: 'Titanic',
    poster: p('titanic'),
    backdrop: p('titanic'),
    year: 1997,
    rating: 4.7,
    maturity: 'PG-13',
    duration: '۳س ۱۴د',
    genres: ['عاشقانه', 'درام'],
    description: 'عشق جک و رز در شب غرق شدن تایتانیک.',
    type: 'Film',
  },
  'the-matrix': {
    id: 'the-matrix',
    titleEn: 'The Matrix',
    titleFa: 'The Matrix',
    poster: p('the-matrix'),
    backdrop: p('the-matrix'),
    year: 1999,
    rating: 4.8,
    maturity: 'R',
    duration: '۲س ۱۶د',
    genres: ['علمی‌تخیلی', 'اکشن'],
    description: 'نئو درمی‌یابد دنیای پیرامونش شبیه‌سازی است و باید انتخاب کند.',
    type: 'Film',
  },
  'lotr-fellowship': {
    id: 'lotr-fellowship',
    titleEn: 'The Lord of the Rings: The Fellowship of the Ring',
    titleFa: 'The Lord of the Rings: The Fellowship of the Ring',
    poster: p('lotr-fellowship'),
    backdrop: p('lotr-fellowship'),
    year: 2001,
    rating: 4.9,
    maturity: 'PG-13',
    duration: '۲س ۵۸د',
    genres: ['فانتزی', 'ماجراجویی'],
    description: 'فروو و یارانش سفر نابودی حلقه یگانه را آغاز می‌کنند.',
    type: 'Film',
  },
  'the-hangover': {
    id: 'the-hangover',
    titleEn: 'The Hangover',
    titleFa: 'The Hangover',
    poster: p('the-hangover'),
    backdrop: p('the-hangover'),
    year: 2009,
    rating: 4.3,
    maturity: 'R',
    duration: '۱س ۴۰د',
    genres: ['کمدی'],
    description: 'سه دوست پس از شب عزیمت در لاس‌وگاس داماد را گم می‌کنند.',
    type: 'Film',
  },
  'wolf-of-wall-street': {
    id: 'wolf-of-wall-street',
    titleEn: 'The Wolf of Wall Street',
    titleFa: 'The Wolf of Wall Street',
    poster: p('wolf-of-wall-street'),
    backdrop: p('wolf-of-wall-street'),
    year: 2013,
    rating: 4.6,
    maturity: 'R',
    duration: '۳س',
    genres: ['کمدی سیاه', 'جنایی'],
    description: 'صعود و سقوط جردن بلفورت در دنیای بورس و زیاده‌روی.',
    type: 'Film',
  },
  'raiders-lost-ark': {
    id: 'raiders-lost-ark',
    titleEn: 'Raiders of the Lost Ark',
    titleFa: 'Raiders of the Lost Ark',
    poster: p('raiders-lost-ark'),
    backdrop: p('raiders-lost-ark'),
    year: 1981,
    rating: 4.8,
    maturity: 'PG',
    duration: '۱س ۵۵د',
    genres: ['ماجراجویی', 'اکشن'],
    description: 'ایندیانا جونز برای یافتن صندوق عهد با نازی‌ها رقابت می‌کند.',
    type: 'Film',
  },
  'shutter-island': {
    id: 'shutter-island',
    titleEn: 'Shutter Island',
    titleFa: 'Shutter Island',
    poster: p('shutter-island'),
    backdrop: p('shutter-island'),
    year: 2010,
    rating: 4.6,
    maturity: 'R',
    duration: '۲س ۱۸د',
    genres: ['معمایی', 'هیجان'],
    description: 'مارشال تدی دانیلز در آسایشگاه جزیره راز بیمار گمشده را می‌کاود.',
    type: 'Film',
  },
  rocky: {
    id: 'rocky',
    titleEn: 'Rocky',
    titleFa: 'Rocky',
    poster: p('rocky'),
    backdrop: p('rocky'),
    year: 1976,
    rating: 4.6,
    maturity: 'PG',
    duration: '۲س',
    genres: ['ورزشی', 'درام'],
    description: 'بوکسور گمنام فیلادلفیا شانس مبارزه با قهرمان جهان را پیدا می‌کند.',
    type: 'Film',
  },
  'django-unchained': {
    id: 'django-unchained',
    titleEn: 'Django Unchained',
    titleFa: 'Django Unchained',
    poster: p('django-unchained'),
    backdrop: p('django-unchained'),
    year: 2012,
    rating: 4.7,
    maturity: 'R',
    duration: '۲س ۴۵د',
    genres: ['وسترن', 'درام'],
    description: 'دجانگو آزادشده با شکارچی جایزه‌بگیر برای نجات همسرش همراه می‌شود.',
    type: 'Film',
  },
  se7en: {
    id: 'se7en',
    titleEn: 'Se7en',
    titleFa: 'Se7en',
    poster: p('se7en'),
    backdrop: p('se7en'),
    year: 1995,
    rating: 4.8,
    maturity: 'R',
    duration: '۲س ۷د',
    genres: ['هیجان', 'جنایی'],
    description: 'دو کارآگاه قاتلی را دنبال می‌کنند که با هفت گناه کبیره قتل می‌کند.',
    type: 'Film',
  },
  'the-dark-knight': {
    id: 'the-dark-knight',
    titleEn: 'The Dark Knight',
    titleFa: 'The Dark Knight',
    poster: p('the-dark-knight'),
    backdrop: p('the-dark-knight'),
    year: 2008,
    rating: 4.9,
    maturity: 'PG-13',
    duration: '۲س ۳۲د',
    genres: ['هیجان‌انگیز', 'اکشن'],
    description: 'بتمن در گاتهام با هرج‌ومرج جوکر روبه‌رو می‌شود.',
    type: 'Film',
  },
}

function t(id: string): SaintstreamTitle {
  const item = titles[id]
  if (!item) throw new Error(`Missing saintstream title: ${id}`)
  return item
}

export const saintstreamHome: SaintstreamHome = {
  heroSlides: [
    t('star-wars-tfa'),
    t('dune-part-two'),
    t('oppenheimer'),
    t('john-wick-4'),
    t('the-last-of-us'),
    t('squid-game'),
  ],
  justRelease: [
    t('spider-verse'),
    t('top-gun-maverick'),
    t('shogun'),
    t('the-batman'),
    t('enola-holmes-2'),
    t('guardians-3'),
    t('arcane'),
  ],
  popularWeek: [
    t('the-last-of-us'),
    t('interstellar'),
    t('stranger-things'),
    t('parasite'),
    t('breaking-bad'),
    t('the-flash'),
  ],
  featured: t('air'),
  featuredSide: [t('dune-part-two'), t('the-last-of-us')],
  movies: [
    t('inception'),
    t('interstellar'),
    t('the-batman'),
    t('john-wick-4'),
    t('avatar-way-of-water'),
    t('everything-everywhere'),
    t('top-gun-maverick'),
    t('air'),
  ],
  series: [
    t('stranger-things'),
    t('breaking-bad'),
    t('dark'),
    t('the-boys'),
    t('wednesday'),
    t('shogun'),
    t('arcane'),
    t('witcher'),
  ],
  koreanSeries: [t('toxic'), t('insider'), t('race'), t('ghost-doctor')],
  award: t('parasite'),
  popularList: [
    t('oppenheimer'),
    t('inception'),
    t('spider-verse'),
    t('guardians-3'),
    t('fall'),
    t('air'),
  ],
  liveList: [
    t('squid-game'),
    t('the-boys'),
    t('sonic-2'),
    t('pathaan'),
    t('black-adam'),
    t('avatar-way-of-water'),
  ],
}

export function getSaintstreamTitle(id: string) {
  return titles[id]
}

export function getAllSaintstreamIds(): string[] {
  return Object.keys(titles)
}

export function getAllSaintstreamTitles(): SaintstreamTitle[] {
  return Object.values(titles)
}

/** Unique genres across Saintstream home catalog (for filter chips) */
export function getSaintstreamGenres(): string[] {
  const set = new Set<string>()
  for (const t of Object.values(titles)) {
    for (const g of t.genres) set.add(g)
  }
  return [...set].sort((a, b) => a.localeCompare(b, 'fa'))
}
