import type { Season } from '@/lib/movies'

export const seriesEpisodes: Record<string, Season[]> = {
  'stranger-things': [
    {
      id: 1,
      title: 'فصل ۱',
      episodes: [
        {
          id: 1,
          title: 'Chapter One: The Vanishing of Will Byers',
          duration: '۴۷ دقیقه',
          description: 'ویل بایرز ناپدید می‌شود و دوستانش جست‌وجو را آغاز می‌کنند.',
          thumbnail: '/saintstream/posters/stranger-things.jpg',
        },
        {
          id: 2,
          title: 'Chapter Two: The Weirdo on Maple Street',
          duration: '۵۵ دقیقه',
          description: 'دختر عجیبی پیدا می‌شود که قدرت‌های غیرعادی دارد.',
          thumbnail: '/saintstream/posters/stranger-things.jpg',
        },
        {
          id: 3,
          title: 'Chapter Three: Holly, Jolly',
          duration: '۵۱ دقیقه',
          description: 'جویس به صدای ویل در دیوارها گوش می‌دهد.',
          thumbnail: '/saintstream/hero/stranger-things.jpg',
        },
        {
          id: 4,
          title: 'Chapter Four: The Body',
          duration: '۵۰ دقیقه',
          description: 'جسد پیدا می‌شود اما جویس باور نمی‌کند.',
          thumbnail: '/saintstream/posters/stranger-things.jpg',
        },
        {
          id: 5,
          title: 'Chapter Five: The Flea and the Acrobat',
          duration: '۵۲ دقیقه',
          description: 'گروه دربارهٔ جهان وارونه نظریه می‌سازد.',
          thumbnail: '/saintstream/posters/stranger-things.jpg',
        },
        {
          id: 6,
          title: 'Chapter Six: The Monster',
          duration: '۴۶ دقیقه',
          description: 'اولین رویارویی جدی با هیولا رخ می‌دهد.',
          thumbnail: '/saintstream/hero/stranger-things.jpg',
        },
        {
          id: 7,
          title: 'Chapter Seven: The Bathtub',
          duration: '۴۱ دقیقه',
          description: 'الون برای یافتن ویل به حس ششم متوسل می‌شود.',
          thumbnail: '/saintstream/posters/stranger-things.jpg',
        },
        {
          id: 8,
          title: 'Chapter Eight: The Upside Down',
          duration: '۵۴ دقیقه',
          description: 'نبرد نهایی فصل برای نجات ویل شکل می‌گیرد.',
          thumbnail: '/saintstream/posters/stranger-things.jpg',
        },
      ],
    },
    {
      id: 2,
      title: 'فصل ۲',
      episodes: [
        {
          id: 1,
          title: 'Chapter One: MADMAX',
          duration: '۴۸ دقیقه',
          description: 'بازگشت به هاوکینز با تهدید تازه آغاز می‌شود.',
          thumbnail: '/saintstream/posters/stranger-things.jpg',
        },
        {
          id: 2,
          title: 'Chapter Two: Trick or Treat, Freak',
          duration: '۵۶ دقیقه',
          description: 'هالووین سایه‌های تاریک‌تری به همراه دارد.',
          thumbnail: '/saintstream/posters/stranger-things.jpg',
        },
        {
          id: 3,
          title: 'Chapter Three: The Pollywog',
          duration: '۵۱ دقیقه',
          description: 'داستین موجودی عجیب پیدا می‌کند.',
          thumbnail: '/saintstream/hero/stranger-things.jpg',
        },
        {
          id: 4,
          title: 'Chapter Four: Will the Wise',
          duration: '۴۶ دقیقه',
          description: 'ویل با رؤیاهای نگران‌کننده روبه‌رو می‌شود.',
          thumbnail: '/saintstream/posters/stranger-things.jpg',
        },
        {
          id: 5,
          title: 'Chapter Five: Dig Dug',
          duration: '۵۸ دقیقه',
          description: 'تونل‌های زیر شهر راز تازه‌ای فاش می‌کنند.',
          thumbnail: '/saintstream/posters/stranger-things.jpg',
        },
        {
          id: 6,
          title: 'Chapter Six: The Spy',
          duration: '۵۱ دقیقه',
          description: 'ویل به ابزاری برای دشمن تبدیل می‌شود.',
          thumbnail: '/saintstream/hero/stranger-things.jpg',
        },
        {
          id: 7,
          title: 'Chapter Seven: The Lost Sister',
          duration: '۴۵ دقیقه',
          description: 'الون با گذشته‌اش روبه‌رو می‌شود.',
          thumbnail: '/saintstream/posters/stranger-things.jpg',
        },
        {
          id: 8,
          title: 'Chapter Eight: The Mind Flayer',
          duration: '۴۷ دقیقه',
          description: 'مایند فلایر چهرهٔ واقعی‌اش را نشان می‌دهد.',
          thumbnail: '/saintstream/posters/stranger-things.jpg',
        },
        {
          id: 9,
          title: 'Chapter Nine: The Gate',
          duration: '۶۲ دقیقه',
          description: 'بستن دروازه تنها راه نجات شهر است.',
          thumbnail: '/saintstream/hero/stranger-things.jpg',
        },
      ],
    },
    {
      id: 3,
      title: 'فصل ۳',
      episodes: [
        {
          id: 1,
          title: 'Chapter One: Suzie, Do You Copy?',
          duration: '۵۰ دقیقه',
          description: 'تابستان داغ هاوکینز با پیام‌های رمزآلود شروع می‌شود.',
          thumbnail: '/saintstream/posters/stranger-things.jpg',
        },
        {
          id: 2,
          title: 'Chapter Two: The Mall Rats',
          duration: '۵۰ دقیقه',
          description: 'مرکز خرید به مرکز توطئه تبدیل می‌شود.',
          thumbnail: '/saintstream/posters/stranger-things.jpg',
        },
        {
          id: 3,
          title: 'Chapter Three: The Case of the Missing Lifeguard',
          duration: '۴۹ دقیقه',
          description: 'ناپدید شدن یک نجات‌غریق راز تازه‌ای می‌سازد.',
          thumbnail: '/saintstream/hero/stranger-things.jpg',
        },
        {
          id: 4,
          title: 'Chapter Four: The Sauna Test',
          duration: '۵۲ دقیقه',
          description: 'آزمایشی خطرناک برای یافتن نفوذی اجرا می‌شود.',
          thumbnail: '/saintstream/posters/stranger-things.jpg',
        },
        {
          id: 5,
          title: 'Chapter Five: The Flayed',
          duration: '۵۱ دقیقه',
          description: 'قربانیان تسخیرشده شهر را تهدید می‌کنند.',
          thumbnail: '/saintstream/posters/stranger-things.jpg',
        },
        {
          id: 6,
          title: 'Chapter Six: E Pluribus Unum',
          duration: '۵۹ دقیقه',
          description: 'اتحاد نیروهای هاوکینز شکل می‌گیرد.',
          thumbnail: '/saintstream/hero/stranger-things.jpg',
        },
        {
          id: 7,
          title: 'Chapter Seven: The Bite',
          duration: '۵۵ دقیقه',
          description: 'زخمی عمیق سرنوشت نبرد را تغییر می‌دهد.',
          thumbnail: '/saintstream/posters/stranger-things.jpg',
        },
        {
          id: 8,
          title: 'Chapter Eight: The Battle of Starcourt',
          duration: '۷۶ دقیقه',
          description: 'نبرد استارکورت سرنوشت فصل را رقم می‌زند.',
          thumbnail: '/saintstream/posters/stranger-things.jpg',
        },
      ],
    },
    {
      id: 4,
      title: 'فصل ۴',
      episodes: [
        {
          id: 1,
          title: 'Chapter One: The Hellfire Club',
          duration: '۷۶ دقیقه',
          description: 'باشگاه جهنمی به مرکز داستان تبدیل می‌شود.',
          thumbnail: '/saintstream/posters/stranger-things.jpg',
        },
        {
          id: 2,
          title: 'Chapter Two: Vecna\'s Curse',
          duration: '۷۵ دقیقه',
          description: 'نفرین وکنا قربانیان تازه‌ای می‌گیرد.',
          thumbnail: '/saintstream/posters/stranger-things.jpg',
        },
        {
          id: 3,
          title: 'Chapter Three: The Monster and the Superhero',
          duration: '۶۳ دقیقه',
          description: 'دو جبهه برای مقابله با تهدید شکل می‌گیرد.',
          thumbnail: '/saintstream/hero/stranger-things.jpg',
        },
        {
          id: 4,
          title: 'Chapter Four: Dear Billy',
          duration: '۷۸ دقیقه',
          description: 'خاطره‌ای دردناک قدرت تازه‌ای آزاد می‌کند.',
          thumbnail: '/saintstream/posters/stranger-things.jpg',
        },
        {
          id: 5,
          title: 'Chapter Five: The Nina Project',
          duration: '۷۴ دقیقه',
          description: 'پروژهٔ نینا گذشتهٔ الون را باز می‌کند.',
          thumbnail: '/saintstream/posters/stranger-things.jpg',
        },
        {
          id: 6,
          title: 'Chapter Six: The Dive',
          duration: '۷۳ دقیقه',
          description: 'غواصی خطرناک برای رسیدن به حقیقت انجام می‌شود.',
          thumbnail: '/saintstream/hero/stranger-things.jpg',
        },
        {
          id: 7,
          title: 'Chapter Seven: The Massacre at Hawkins Lab',
          duration: '۹۸ دقیقه',
          description: 'کشتار آزمایشگاه هاوکینز فاش می‌شود.',
          thumbnail: '/saintstream/posters/stranger-things.jpg',
        },
        {
          id: 8,
          title: 'Chapter Eight: Papa',
          duration: '۸۴ دقیقه',
          description: 'مواجهه با پاپا سرنوشت الون را تغییر می‌دهد.',
          thumbnail: '/saintstream/posters/stranger-things.jpg',
        },
        {
          id: 9,
          title: 'Chapter Nine: The Piggyback',
          duration: '۱۳۹ دقیقه',
          description: 'حملهٔ نهایی به وکنا آغاز می‌شود.',
          thumbnail: '/saintstream/hero/stranger-things.jpg',
        },
      ],
    },
    {
      id: 5,
      title: 'فصل ۵',
      episodes: [
        {
          id: 1,
          title: 'Chapter One: The Crawl',
          duration: '۶۸ دقیقه',
          description: 'هاوکینز در سایهٔ تهدید تازه نفس می‌کشد.',
          thumbnail: '/saintstream/posters/stranger-things.jpg',
        },
        {
          id: 2,
          title: 'Chapter Two: The Vanishing of Holly Wheeler',
          duration: '۶۰ دقیقه',
          description: 'ناپدید شدن هالی وحشت تازه‌ای می‌آفریند.',
          thumbnail: '/saintstream/posters/stranger-things.jpg',
        },
        {
          id: 3,
          title: 'Chapter Three: The Turnbow Trap',
          duration: '۶۴ دقیقه',
          description: 'تله‌ای برای به دام انداختن دشمن چیده می‌شود.',
          thumbnail: '/saintstream/hero/stranger-things.jpg',
        },
        {
          id: 4,
          title: 'Chapter Four: Sorcerer',
          duration: '۷۲ دقیقه',
          description: 'قدرت‌های جادویی در نبرد نقش کلیدی پیدا می‌کنند.',
          thumbnail: '/saintstream/posters/stranger-things.jpg',
        },
        {
          id: 5,
          title: 'Chapter Five: Shock Jock',
          duration: '۶۶ دقیقه',
          description: 'پیامی شوکه‌کننده مسیر گروه را عوض می‌کند.',
          thumbnail: '/saintstream/posters/stranger-things.jpg',
        },
        {
          id: 6,
          title: 'Chapter Six: Escape from Camazotz',
          duration: '۷۰ دقیقه',
          description: 'فرار از کامازوتز آخرین امید می‌شود.',
          thumbnail: '/saintstream/hero/stranger-things.jpg',
        },
        {
          id: 7,
          title: 'Chapter Seven: The Bridge',
          duration: '۷۴ دقیقه',
          description: 'پل میان دو جهان باز می‌شود.',
          thumbnail: '/saintstream/posters/stranger-things.jpg',
        },
        {
          id: 8,
          title: 'Chapter Eight: The Rightside Up',
          duration: '۱۲۰ دقیقه',
          description: 'نبرد نهایی برای بازگرداندن نظم جهان.',
          thumbnail: '/saintstream/posters/stranger-things.jpg',
        },
      ],
    },
  ],
  'breaking-bad': [
    {
      id: 1,
      title: 'فصل ۱',
      episodes: [
        {
          id: 1,
          title: 'Pilot',
          duration: '۵۸ دقیقه',
          description: 'والتر وایت با تشخیص سرطان تصمیم خطرناکی می‌گیرد.',
          thumbnail: '/saintstream/posters/breaking-bad.jpg',
        },
        {
          id: 2,
          title: 'Cat\'s in the Bag...',
          duration: '۴۸ دقیقه',
          description: 'پیامدهای اولین پخت گریبان‌گیر می‌شود.',
          thumbnail: '/saintstream/posters/breaking-bad.jpg',
        },
        {
          id: 3,
          title: '...And the Bag\'s in the River',
          duration: '۴۸ دقیقه',
          description: 'والت باید با عواقب اخلاقی کارش روبه‌رو شود.',
          thumbnail: '/saintstream/hero/breaking-bad.jpg',
        },
        {
          id: 4,
          title: 'Cancer Man',
          duration: '۴۸ دقیقه',
          description: 'خبر سرطان خانواده را متزلزل می‌کند.',
          thumbnail: '/saintstream/posters/breaking-bad.jpg',
        },
        {
          id: 5,
          title: 'Gray Matter',
          duration: '۴۸ دقیقه',
          description: 'گذشتهٔ علمی والت دوباره سر برمی‌آورد.',
          thumbnail: '/saintstream/posters/breaking-bad.jpg',
        },
        {
          id: 6,
          title: 'Crazy Handful of Nothin\'',
          duration: '۴۸ دقیقه',
          description: 'والت چهرهٔ تازه‌ای از خودش نشان می‌دهد.',
          thumbnail: '/saintstream/hero/breaking-bad.jpg',
        },
        {
          id: 7,
          title: 'A No-Rough-Stuff-Type Deal',
          duration: '۴۷ دقیقه',
          description: 'شراکت خطرناک شکل جدی‌تری می‌گیرد.',
          thumbnail: '/saintstream/posters/breaking-bad.jpg',
        },
      ],
    },
    {
      id: 2,
      title: 'فصل ۲',
      episodes: [
        {
          id: 1,
          title: 'Seven Thirty-Seven',
          duration: '۴۷ دقیقه',
          description: 'فشار روحی والت پس از خشونت اوج می‌گیرد.',
          thumbnail: '/saintstream/posters/breaking-bad.jpg',
        },
        {
          id: 2,
          title: 'Grilled',
          duration: '۴۸ دقیقه',
          description: 'اسیر شدن نزد تیوکو همه‌چیز را تهدید می‌کند.',
          thumbnail: '/saintstream/posters/breaking-bad.jpg',
        },
        {
          id: 3,
          title: 'Bit by a Dead Bee',
          duration: '۴۷ دقیقه',
          description: 'بازگشت از بحران با دروغ‌های تازه همراه است.',
          thumbnail: '/saintstream/hero/breaking-bad.jpg',
        },
        {
          id: 4,
          title: 'Down',
          duration: '۴۷ دقیقه',
          description: 'والت برای حفظ ظاهر در خانه می‌جنگد.',
          thumbnail: '/saintstream/posters/breaking-bad.jpg',
        },
        {
          id: 5,
          title: 'Breakage',
          duration: '۴۷ دقیقه',
          description: 'جسِه شبکهٔ فروش تازه‌ای می‌سازد.',
          thumbnail: '/saintstream/posters/breaking-bad.jpg',
        },
        {
          id: 6,
          title: 'Peekaboo',
          duration: '۴۷ دقیقه',
          description: 'جسِه با خانواده‌ای ویران روبه‌رو می‌شود.',
          thumbnail: '/saintstream/hero/breaking-bad.jpg',
        },
        {
          id: 7,
          title: 'Negro y Azul',
          duration: '۴۷ دقیقه',
          description: 'آوازهٔ هایزنبرگ در خیابان می‌پیچد.',
          thumbnail: '/saintstream/posters/breaking-bad.jpg',
        },
        {
          id: 8,
          title: 'Better Call Saul',
          duration: '۴۷ دقیقه',
          description: 'وکیل حیله‌گر وارد بازی می‌شود.',
          thumbnail: '/saintstream/posters/breaking-bad.jpg',
        },
        {
          id: 9,
          title: '4 Days Out',
          duration: '۴۷ دقیقه',
          description: 'پخت طولانی در بیابان همه را خسته می‌کند.',
          thumbnail: '/saintstream/hero/breaking-bad.jpg',
        },
        {
          id: 10,
          title: 'Over',
          duration: '۴۷ دقیقه',
          description: 'والت وانمود می‌کند کار را تمام کرده است.',
          thumbnail: '/saintstream/posters/breaking-bad.jpg',
        },
        {
          id: 11,
          title: 'Mandala',
          duration: '۴۷ دقیقه',
          description: 'گاس فرینگ پیشنهاد وسوسه‌انگیزی می‌دهد.',
          thumbnail: '/saintstream/posters/breaking-bad.jpg',
        },
        {
          id: 12,
          title: 'Phoenix',
          duration: '۴۷ دقیقه',
          description: 'تراژدی جین زندگی جسِه را دگرگون می‌کند.',
          thumbnail: '/saintstream/hero/breaking-bad.jpg',
        },
        {
          id: 13,
          title: 'ABQ',
          duration: '۴۷ دقیقه',
          description: 'سقوط هواپیما زخم‌های شهر را عمیق‌تر می‌کند.',
          thumbnail: '/saintstream/posters/breaking-bad.jpg',
        },
      ],
    },
    {
      id: 3,
      title: 'فصل ۳',
      episodes: [
        {
          id: 1,
          title: 'No Más',
          duration: '۴۷ دقیقه',
          description: 'والت به نیومکزیکو بازمی‌گردد تا کار را ادامه دهد.',
          thumbnail: '/saintstream/posters/breaking-bad.jpg',
        },
        {
          id: 2,
          title: 'Caballo Sin Nombre',
          duration: '۴۷ دقیقه',
          description: 'بازگشت به خانه با تنش خانوادگی همراه است.',
          thumbnail: '/saintstream/posters/breaking-bad.jpg',
        },
        {
          id: 3,
          title: 'I.F.T.',
          duration: '۴۷ دقیقه',
          description: 'اسکایلر تصمیمی تکان‌دهنده می‌گیرد.',
          thumbnail: '/saintstream/hero/breaking-bad.jpg',
        },
        {
          id: 4,
          title: 'Green Light',
          duration: '۴۷ دقیقه',
          description: 'رقابت در آزمایشگاه شدت می‌گیرد.',
          thumbnail: '/saintstream/posters/breaking-bad.jpg',
        },
        {
          id: 5,
          title: 'Más',
          duration: '۴۷ دقیقه',
          description: 'گاس شرایط کار را سخت‌تر می‌کند.',
          thumbnail: '/saintstream/posters/breaking-bad.jpg',
        },
        {
          id: 6,
          title: 'Sunset',
          duration: '۴۷ دقیقه',
          description: 'گِیل به تیم اضافه می‌شود و تهدید تازه می‌آید.',
          thumbnail: '/saintstream/hero/breaking-bad.jpg',
        },
        {
          id: 7,
          title: 'One Minute',
          duration: '۴۷ دقیقه',
          description: 'هنک در تیراندازی مرگباری گیر می‌افتد.',
          thumbnail: '/saintstream/posters/breaking-bad.jpg',
        },
        {
          id: 8,
          title: 'I See You',
          duration: '۴۷ دقیقه',
          description: 'بیمارستان صحنهٔ تنش‌های تازه می‌شود.',
          thumbnail: '/saintstream/posters/breaking-bad.jpg',
        },
        {
          id: 9,
          title: 'Kafkaesque',
          duration: '۴۷ دقیقه',
          description: 'جسِه برای پولشاخ‌تر شدن نقشه می‌کشد.',
          thumbnail: '/saintstream/hero/breaking-bad.jpg',
        },
        {
          id: 10,
          title: 'Fly',
          duration: '۴۷ دقیقه',
          description: 'مگسی ساده والت را تا مرز جنون می‌برد.',
          thumbnail: '/saintstream/posters/breaking-bad.jpg',
        },
        {
          id: 11,
          title: 'Abiquiu',
          duration: '۴۷ دقیقه',
          description: 'جسِه با خاطرات جین روبه‌رو می‌شود.',
          thumbnail: '/saintstream/posters/breaking-bad.jpg',
        },
        {
          id: 12,
          title: 'Half Measures',
          duration: '۴۷ دقیقه',
          description: 'والت میان اخلاق و بقا گیر می‌کند.',
          thumbnail: '/saintstream/hero/breaking-bad.jpg',
        },
        {
          id: 13,
          title: 'Full Measure',
          duration: '۴۷ دقیقه',
          description: 'تصمیمی خونین مسیر سریال را عوض می‌کند.',
          thumbnail: '/saintstream/posters/breaking-bad.jpg',
        },
      ],
    },
    {
      id: 4,
      title: 'فصل ۴',
      episodes: [
        {
          id: 1,
          title: 'Box Cutter',
          duration: '۴۷ دقیقه',
          description: 'گاس قدرتش را با خشونت محض نشان می‌دهد.',
          thumbnail: '/saintstream/posters/breaking-bad.jpg',
        },
        {
          id: 2,
          title: 'Thirty-Eight Snub',
          duration: '۴۷ دقیقه',
          description: 'والت برای حفاظت از خودش اسلحه می‌خرد.',
          thumbnail: '/saintstream/posters/breaking-bad.jpg',
        },
        {
          id: 3,
          title: 'Open House',
          duration: '۴۷ دقیقه',
          description: 'اسکایلر خانه‌ها را برای پولشویی بازدید می‌کند.',
          thumbnail: '/saintstream/hero/breaking-bad.jpg',
        },
        {
          id: 4,
          title: 'Bullet Points',
          duration: '۴۷ دقیقه',
          description: 'هنک پروندهٔ هایزنبرگ را جدی‌تر دنبال می‌کند.',
          thumbnail: '/saintstream/posters/breaking-bad.jpg',
        },
        {
          id: 5,
          title: 'Shotgun',
          duration: '۴۷ دقیقه',
          description: 'جسِه با مایک وارد مأموریت‌های خطرناک می‌شود.',
          thumbnail: '/saintstream/posters/breaking-bad.jpg',
        },
        {
          id: 6,
          title: 'Cornered',
          duration: '۴۷ دقیقه',
          description: 'والت ادعا می‌کند خطرناک‌ترین فرد اتاق است.',
          thumbnail: '/saintstream/hero/breaking-bad.jpg',
        },
        {
          id: 7,
          title: 'Problem Dog',
          duration: '۴۷ دقیقه',
          description: 'جسِه در گروه حمایتی حقیقت تلخی می‌گوید.',
          thumbnail: '/saintstream/posters/breaking-bad.jpg',
        },
        {
          id: 8,
          title: 'Hermanos',
          duration: '۴۷ دقیقه',
          description: 'داستان گذشتهٔ گاس فاش می‌شود.',
          thumbnail: '/saintstream/posters/breaking-bad.jpg',
        },
        {
          id: 9,
          title: 'Bug',
          duration: '۴۷ دقیقه',
          description: 'شکاف میان والت و جسِه عمیق‌تر می‌شود.',
          thumbnail: '/saintstream/hero/breaking-bad.jpg',
        },
        {
          id: 10,
          title: 'Salud',
          duration: '۴۷ دقیقه',
          description: 'پخت در مکزیکو به فاجعه ختم می‌شود.',
          thumbnail: '/saintstream/posters/breaking-bad.jpg',
        },
        {
          id: 11,
          title: 'Crawl Space',
          duration: '۴۷ دقیقه',
          description: 'والت در ترس از انتقام گاس فرو می‌رود.',
          thumbnail: '/saintstream/posters/breaking-bad.jpg',
        },
        {
          id: 12,
          title: 'End Times',
          duration: '۴۷ دقیقه',
          description: 'تهدید بمب همه‌چیز را به لب پرتگاه می‌برد.',
          thumbnail: '/saintstream/hero/breaking-bad.jpg',
        },
        {
          id: 13,
          title: 'Face Off',
          duration: '۵۰ دقیقه',
          description: 'نبرد نهایی با گاس رقم می‌خورد.',
          thumbnail: '/saintstream/posters/breaking-bad.jpg',
        },
      ],
    },
    {
      id: 5,
      title: 'فصل ۵',
      episodes: [
        {
          id: 1,
          title: 'Live Free or Die',
          duration: '۴۲ دقیقه',
          description: 'پس از سقوط گاس، والت امپراتوری تازه‌ای می‌سازد.',
          thumbnail: '/saintstream/posters/breaking-bad.jpg',
        },
        {
          id: 2,
          title: 'Madrigal',
          duration: '۴۷ دقیقه',
          description: 'مایک و رده‌های شرکت مادیگال وارد می‌شوند.',
          thumbnail: '/saintstream/posters/breaking-bad.jpg',
        },
        {
          id: 3,
          title: 'Hazard Pay',
          duration: '۴۷ دقیقه',
          description: 'تیم تازه‌ای برای پخت شکل می‌گیرد.',
          thumbnail: '/saintstream/hero/breaking-bad.jpg',
        },
        {
          id: 4,
          title: 'Fifty-One',
          duration: '۴۷ دقیقه',
          description: 'تولد ۵۱ سالگی والت با تنش خانوادگی همراه است.',
          thumbnail: '/saintstream/posters/breaking-bad.jpg',
        },
        {
          id: 5,
          title: 'Dead Freight',
          duration: '۴۸ دقیقه',
          description: 'سرقت قطار ریسکی بزرگ رقم می‌زند.',
          thumbnail: '/saintstream/posters/breaking-bad.jpg',
        },
        {
          id: 6,
          title: 'Buyout',
          duration: '۴۷ دقیقه',
          description: 'پیشنهاد خرید سهم‌ها درگیری ایجاد می‌کند.',
          thumbnail: '/saintstream/hero/breaking-bad.jpg',
        },
        {
          id: 7,
          title: 'Say My Name',
          duration: '۴۷ دقیقه',
          description: 'والت قدرت نام هایزنبرگ را به رخ می‌کشد.',
          thumbnail: '/saintstream/posters/breaking-bad.jpg',
        },
        {
          id: 8,
          title: 'Gliding Over All',
          duration: '۴۷ دقیقه',
          description: 'امپراتوری به اوج می‌رسد و سپس شکاف می‌خورد.',
          thumbnail: '/saintstream/posters/breaking-bad.jpg',
        },
        {
          id: 9,
          title: 'Blood Money',
          duration: '۴۷ دقیقه',
          description: 'هنک سرانجام حقیقت را می‌فهمد.',
          thumbnail: '/saintstream/hero/breaking-bad.jpg',
        },
        {
          id: 10,
          title: 'Buried',
          duration: '۴۷ دقیقه',
          description: 'پول دفن‌شده و رازهای تازه سر برمی‌آورند.',
          thumbnail: '/saintstream/posters/breaking-bad.jpg',
        },
        {
          id: 11,
          title: 'Confessions',
          duration: '۴۷ دقیقه',
          description: 'اعتراف‌های ساختگی روابط را ویران می‌کند.',
          thumbnail: '/saintstream/posters/breaking-bad.jpg',
        },
        {
          id: 12,
          title: 'Rabid Dog',
          duration: '۴۷ دقیقه',
          description: 'جسِه تصمیم به مقابله می‌گیرد.',
          thumbnail: '/saintstream/hero/breaking-bad.jpg',
        },
        {
          id: 13,
          title: 'To\'hajiilee',
          duration: '۴۷ دقیقه',
          description: 'تعقیب در صحرا به تیراندازی ختم می‌شود.',
          thumbnail: '/saintstream/posters/breaking-bad.jpg',
        },
        {
          id: 14,
          title: 'Ozymandias',
          duration: '۴۷ دقیقه',
          description: 'همه‌چیز برای خانوادهٔ وایت فرو می‌پاشد.',
          thumbnail: '/saintstream/posters/breaking-bad.jpg',
        },
        {
          id: 15,
          title: 'Granite State',
          duration: '۵۳ دقیقه',
          description: 'والت در انزوای سرد پنهان می‌شود.',
          thumbnail: '/saintstream/hero/breaking-bad.jpg',
        },
        {
          id: 16,
          title: 'Felina',
          duration: '۵۵ دقیقه',
          description: 'بازگشت نهایی والت برای تسویه‌حساب.',
          thumbnail: '/saintstream/posters/breaking-bad.jpg',
        },
      ],
    },
  ],
  'dark': [
    {
      id: 1,
      title: 'فصل ۱',
      episodes: [
        {
          id: 1,
          title: 'Secrets',
          duration: '۵۱ دقیقه',
          description: 'ناپدید شدن یک نوجوان شهر ویندن را متلاطم می‌کند.',
          thumbnail: '/saintstream/posters/dark.jpg',
        },
        {
          id: 2,
          title: 'Lies',
          duration: '۴۴ دقیقه',
          description: 'دروغ‌های خانوادگی لایه‌لایه باز می‌شوند.',
          thumbnail: '/saintstream/posters/dark.jpg',
        },
        {
          id: 3,
          title: 'Past and Present',
          duration: '۴۵ دقیقه',
          description: 'گذشته و حال در هم تنیده می‌شوند.',
          thumbnail: '/saintstream/hero/dark.jpg',
        },
        {
          id: 4,
          title: 'Double Lives',
          duration: '۴۷ دقیقه',
          description: 'زندگی دوگانه شخصیت‌ها فاش می‌شود.',
          thumbnail: '/saintstream/posters/dark.jpg',
        },
        {
          id: 5,
          title: 'Truths',
          duration: '۴۸ دقیقه',
          description: 'حقیقتی تلخ دربارهٔ غارها آشکار می‌شود.',
          thumbnail: '/saintstream/posters/dark.jpg',
        },
        {
          id: 6,
          title: 'Sic Mundus Creatus Est',
          duration: '۵۰ دقیقه',
          description: 'انجمن مرموز وارد داستان می‌شود.',
          thumbnail: '/saintstream/hero/dark.jpg',
        },
        {
          id: 7,
          title: 'Crossroads',
          duration: '۵۱ دقیقه',
          description: 'انتخاب‌ها مسیر زمان را تغییر می‌دهند.',
          thumbnail: '/saintstream/posters/dark.jpg',
        },
        {
          id: 8,
          title: 'As You Sow, so You Shall Reap',
          duration: '۴۹ دقیقه',
          description: 'مسافر زمان پیامد کارش را می‌بیند.',
          thumbnail: '/saintstream/posters/dark.jpg',
        },
        {
          id: 9,
          title: 'Everything Is Now',
          duration: '۵۴ دقیقه',
          description: 'همه‌چیز هم‌زمان رخ می‌دهد.',
          thumbnail: '/saintstream/hero/dark.jpg',
        },
        {
          id: 10,
          title: 'Alpha and Omega',
          duration: '۵۶ دقیقه',
          description: 'آغاز و پایان در یک نقطه به هم می‌رسند.',
          thumbnail: '/saintstream/posters/dark.jpg',
        },
      ],
    },
    {
      id: 2,
      title: 'فصل ۲',
      episodes: [
        {
          id: 1,
          title: 'Beginnings and Endings',
          duration: '۵۳ دقیقه',
          description: 'فصل تازه با آپوکالیپس نزدیک می‌شود.',
          thumbnail: '/saintstream/posters/dark.jpg',
        },
        {
          id: 2,
          title: 'Dark Matter',
          duration: '۵۴ دقیقه',
          description: 'ماده تاریک راز سفر زمانی را روشن می‌کند.',
          thumbnail: '/saintstream/posters/dark.jpg',
        },
        {
          id: 3,
          title: 'Ghosts',
          duration: '۵۴ دقیقه',
          description: 'سایه‌های گذشته شخصیت‌ها را تعقیب می‌کنند.',
          thumbnail: '/saintstream/hero/dark.jpg',
        },
        {
          id: 4,
          title: 'The Travelers',
          duration: '۵۵ دقیقه',
          description: 'مسافران زمان قوانین را می‌شکنند.',
          thumbnail: '/saintstream/posters/dark.jpg',
        },
        {
          id: 5,
          title: 'Lost and Found',
          duration: '۵۶ دقیقه',
          description: 'گمشده‌ها و یافته‌ها جای خود را عوض می‌کنند.',
          thumbnail: '/saintstream/posters/dark.jpg',
        },
        {
          id: 6,
          title: 'An Endless Cycle',
          duration: '۵۶ دقیقه',
          description: 'چرخه بی‌پایان سرنوشت تکرار می‌شود.',
          thumbnail: '/saintstream/hero/dark.jpg',
        },
        {
          id: 7,
          title: 'The White Devil',
          duration: '۵۷ دقیقه',
          description: 'شیطان سفید چهره نشان می‌دهد.',
          thumbnail: '/saintstream/posters/dark.jpg',
        },
        {
          id: 8,
          title: 'End and Beginning',
          duration: '۶۰ دقیقه',
          description: 'پایان به آغاز تازه‌ای تبدیل می‌شود.',
          thumbnail: '/saintstream/posters/dark.jpg',
        },
      ],
    },
    {
      id: 3,
      title: 'فصل ۳',
      episodes: [
        {
          id: 1,
          title: 'Deja-vu',
          duration: '۶۰ دقیقه',
          description: 'جهان موازی همه چیز را پیچیده‌تر می‌کند.',
          thumbnail: '/saintstream/posters/dark.jpg',
        },
        {
          id: 2,
          title: 'The Survivors',
          duration: '۵۸ دقیقه',
          description: 'بازماندگان آپوکالیپس گرد هم می‌آیند.',
          thumbnail: '/saintstream/posters/dark.jpg',
        },
        {
          id: 3,
          title: 'Adam and Eva',
          duration: '۵۹ دقیقه',
          description: 'آدام و اوا دو سوی جنگ زمان‌اند.',
          thumbnail: '/saintstream/hero/dark.jpg',
        },
        {
          id: 4,
          title: 'The Origin',
          duration: '۶۱ دقیقه',
          description: 'منشأ گره زمانی فاش می‌شود.',
          thumbnail: '/saintstream/posters/dark.jpg',
        },
        {
          id: 5,
          title: 'Life and Death',
          duration: '۵۸ دقیقه',
          description: 'مرز زندگی و مرگ محو می‌شود.',
          thumbnail: '/saintstream/posters/dark.jpg',
        },
        {
          id: 6,
          title: 'Light and Darkness',
          duration: '۶۰ دقیقه',
          description: 'نور و تاریکی برای کنترل آینده می‌جنگند.',
          thumbnail: '/saintstream/hero/dark.jpg',
        },
        {
          id: 7,
          title: 'Between the Time',
          duration: '۶۲ دقیقه',
          description: 'میان زمان‌ها تنها یک راه باقی می‌ماند.',
          thumbnail: '/saintstream/posters/dark.jpg',
        },
        {
          id: 8,
          title: 'The Paradise',
          duration: '۷۰ دقیقه',
          description: 'بهشت موعود بهای سنگینی دارد.',
          thumbnail: '/saintstream/posters/dark.jpg',
        },
      ],
    },
  ],
  'the-boys': [
    {
      id: 1,
      title: 'فصل ۱',
      episodes: [
        {
          id: 1,
          title: 'The Name of the Game',
          duration: '۶۰ دقیقه',
          description: 'گروه پسربچه‌ها با دنیای ابرقهرمانان فاسد روبه‌رو می‌شود.',
          thumbnail: '/saintstream/posters/the-boys.jpg',
        },
        {
          id: 2,
          title: 'Cherry',
          duration: '۶۰ دقیقه',
          description: 'هیووی وارد تیمی می‌شود که قانون خودش را دارد.',
          thumbnail: '/saintstream/posters/the-boys.jpg',
        },
        {
          id: 3,
          title: 'Get Some',
          duration: '۵۵ دقیقه',
          description: 'نبرد خیابانی تصویر عمومی سوپ‌ها را می‌شکند.',
          thumbnail: '/saintstream/hero/the-boys.jpg',
        },
        {
          id: 4,
          title: 'The Female of the Species',
          duration: '۵۶ دقیقه',
          description: 'زن مرموزی با قدرت مرگبار وارد داستان می‌شود.',
          thumbnail: '/saintstream/posters/the-boys.jpg',
        },
        {
          id: 5,
          title: 'Good for the Soul',
          duration: '۶۰ دقیقه',
          description: 'رویداد خیریه نقاب ریاکاری را کنار می‌زند.',
          thumbnail: '/saintstream/posters/the-boys.jpg',
        },
        {
          id: 6,
          title: 'The Innocents',
          duration: '۶۰ دقیقه',
          description: 'بی‌گناهان بهای قدرت سوپ‌ها را می‌پردازند.',
          thumbnail: '/saintstream/hero/the-boys.jpg',
        },
        {
          id: 7,
          title: 'The Self-Preservation Society',
          duration: '۵۸ دقیقه',
          description: 'بقای شخصی بر وفاداری غالب می‌شود.',
          thumbnail: '/saintstream/posters/the-boys.jpg',
        },
        {
          id: 8,
          title: 'You Found Me',
          duration: '۶۶ دقیقه',
          description: 'مواجهه نهایی فصل با هوملندر رقم می‌خورد.',
          thumbnail: '/saintstream/posters/the-boys.jpg',
        },
      ],
    },
    {
      id: 2,
      title: 'فصل ۲',
      episodes: [
        {
          id: 1,
          title: 'The Big Ride',
          duration: '۶۰ دقیقه',
          description: 'جنگ با ووت بزرگ‌تر و شخصی‌تر می‌شود.',
          thumbnail: '/saintstream/posters/the-boys.jpg',
        },
        {
          id: 2,
          title: 'Proper Preparation and Planning',
          duration: '۶۰ دقیقه',
          description: 'نقشه‌ای دقیق برای ضربه به سوپ‌ها چیده می‌شود.',
          thumbnail: '/saintstream/posters/the-boys.jpg',
        },
        {
          id: 3,
          title: 'Over the Hill with the Swords of a Thousand Men',
          duration: '۶۰ دقیقه',
          description: 'خشونت به سطحی تازه می‌رسد.',
          thumbnail: '/saintstream/hero/the-boys.jpg',
        },
        {
          id: 4,
          title: 'Nothing Like It in the World',
          duration: '۶۰ دقیقه',
          description: 'قدرت‌های تازه‌ای بازار را به هم می‌ریزند.',
          thumbnail: '/saintstream/posters/the-boys.jpg',
        },
        {
          id: 5,
          title: 'We Gotta Go Now',
          duration: '۶۱ دقیقه',
          description: 'فرار و تعقیب سرعت داستان را بالا می‌برد.',
          thumbnail: '/saintstream/posters/the-boys.jpg',
        },
        {
          id: 6,
          title: 'The Bloody Doors Off',
          duration: '۶۰ دقیقه',
          description: 'افشای رازها درهای خونین را باز می‌کند.',
          thumbnail: '/saintstream/hero/the-boys.jpg',
        },
        {
          id: 7,
          title: 'Butcher, Baker, Candlestick Maker',
          duration: '۶۲ دقیقه',
          description: 'گذشتهٔ بوچر روشن‌تر می‌شود.',
          thumbnail: '/saintstream/posters/the-boys.jpg',
        },
        {
          id: 8,
          title: 'What I Know',
          duration: '۶۸ دقیقه',
          description: 'دانسته‌های تازه مسیر جنگ را عوض می‌کنند.',
          thumbnail: '/saintstream/posters/the-boys.jpg',
        },
      ],
    },
    {
      id: 3,
      title: 'فصل ۳',
      episodes: [
        {
          id: 1,
          title: 'Payback',
          duration: '۶۱ دقیقه',
          description: 'انتقام موتور اصلی فصل سوم می‌شود.',
          thumbnail: '/saintstream/posters/the-boys.jpg',
        },
        {
          id: 2,
          title: 'The Only Man in the Sky',
          duration: '۶۰ دقیقه',
          description: 'هوملندر تصویر خدایی‌اش را تقویت می‌کند.',
          thumbnail: '/saintstream/posters/the-boys.jpg',
        },
        {
          id: 3,
          title: 'Barbary Coast',
          duration: '۵۹ دقیقه',
          description: 'ائتلاف‌های تازه در ساحل بربری شکل می‌گیرند.',
          thumbnail: '/saintstream/hero/the-boys.jpg',
        },
        {
          id: 4,
          title: 'Glorious Five Year Plan',
          duration: '۶۰ دقیقه',
          description: 'نقشه پنج‌ساله ووت ترک برمی‌دارد.',
          thumbnail: '/saintstream/posters/the-boys.jpg',
        },
        {
          id: 5,
          title: 'The Last Time to Look on This World of Lies',
          duration: '۶۰ دقیقه',
          description: 'دنیای دروغ آخرین فرصت را می‌دهد.',
          thumbnail: '/saintstream/posters/the-boys.jpg',
        },
        {
          id: 6,
          title: 'Herogasm',
          duration: '۶۲ دقیقه',
          description: 'مهمانی ابرقهرمانی به فاجعه تبدیل می‌شود.',
          thumbnail: '/saintstream/hero/the-boys.jpg',
        },
        {
          id: 7,
          title: 'Here Comes a Candle to Light You to Bed',
          duration: '۶۳ دقیقه',
          description: 'شمعی برای بدرقه به تاریکی روشن می‌شود.',
          thumbnail: '/saintstream/posters/the-boys.jpg',
        },
        {
          id: 8,
          title: 'The Instant White-Hot Wild',
          duration: '۶۵ دقیقه',
          description: 'خشم سفید و سوزان همه‌چیز را می‌سوزاند.',
          thumbnail: '/saintstream/posters/the-boys.jpg',
        },
      ],
    },
    {
      id: 4,
      title: 'فصل ۴',
      episodes: [
        {
          id: 1,
          title: 'Department of Dirty Tricks',
          duration: '۶۲ دقیقه',
          description: 'وزارت حقه‌های کثیف وارد بازی می‌شود.',
          thumbnail: '/saintstream/posters/the-boys.jpg',
        },
        {
          id: 2,
          title: 'Life Among the Septics',
          duration: '۶۰ دقیقه',
          description: 'زندگی میان گنداب سیاست سخت‌تر می‌شود.',
          thumbnail: '/saintstream/posters/the-boys.jpg',
        },
        {
          id: 3,
          title: 'We\'ll Keep the Red Flag Flying Here',
          duration: '۶۱ دقیقه',
          description: 'پرچم سرخ نماد اتحاد تازه می‌شود.',
          thumbnail: '/saintstream/hero/the-boys.jpg',
        },
        {
          id: 4,
          title: 'Wisdom of the Ages',
          duration: '۶۰ دقیقه',
          description: 'خرد اعصار رازهای کهنه را باز می‌کند.',
          thumbnail: '/saintstream/posters/the-boys.jpg',
        },
        {
          id: 5,
          title: 'Beware the Jabberwock, My Son',
          duration: '۶۳ دقیقه',
          description: 'هیولای تازه‌ای از افسانه‌ها سر برمی‌آورد.',
          thumbnail: '/saintstream/posters/the-boys.jpg',
        },
        {
          id: 6,
          title: 'Dirty Business',
          duration: '۶۱ دقیقه',
          description: 'کسب‌وکار کثیف ووت افشا می‌شود.',
          thumbnail: '/saintstream/hero/the-boys.jpg',
        },
        {
          id: 7,
          title: 'The Insider',
          duration: '۶۴ دقیقه',
          description: 'نفوذی درون سیستم همه‌چیز را می‌لرزاند.',
          thumbnail: '/saintstream/posters/the-boys.jpg',
        },
        {
          id: 8,
          title: 'Assassination Run',
          duration: '۷۰ دقیقه',
          description: 'عملیات ترور به نقطه جوش می‌رسد.',
          thumbnail: '/saintstream/posters/the-boys.jpg',
        },
      ],
    },
  ],
  'wednesday': [
    {
      id: 1,
      title: 'فصل ۱',
      episodes: [
        {
          id: 1,
          title: 'Wednesday\'s Child Is Full of Woe',
          duration: '۵۱ دقیقه',
          description: 'ونزدی به آکادمی نِورمور می‌رود.',
          thumbnail: '/saintstream/posters/wednesday.jpg',
        },
        {
          id: 2,
          title: 'Woe Is the Loneliest Number',
          duration: '۵۰ دقیقه',
          description: 'اولین رمز قتل‌ها آشکار می‌شود.',
          thumbnail: '/saintstream/posters/wednesday.jpg',
        },
        {
          id: 3,
          title: 'Friend or Woe',
          duration: '۴۹ دقیقه',
          description: 'دوستی تازه مرزهای ونزدی را می‌آزماید.',
          thumbnail: '/saintstream/hero/wednesday.jpg',
        },
        {
          id: 4,
          title: 'Woe What a Night',
          duration: '۵۰ دقیقه',
          description: 'شبی پرماجرا راز مدرسه را نزدیک‌تر می‌کند.',
          thumbnail: '/saintstream/posters/wednesday.jpg',
        },
        {
          id: 5,
          title: 'You Reap What You Woe',
          duration: '۵۱ دقیقه',
          description: 'نتیجهٔ انتخاب‌های گذشته سر می‌رسد.',
          thumbnail: '/saintstream/posters/wednesday.jpg',
        },
        {
          id: 6,
          title: 'Quid Pro Woe',
          duration: '۵۲ دقیقه',
          description: 'معامله‌ای خطرناک شکل می‌گیرد.',
          thumbnail: '/saintstream/hero/wednesday.jpg',
        },
        {
          id: 7,
          title: 'If You Don\'t Woe Me by Now',
          duration: '۴۸ دقیقه',
          description: 'اتحادها در آستانه فروپاشی‌اند.',
          thumbnail: '/saintstream/posters/wednesday.jpg',
        },
        {
          id: 8,
          title: 'A Murder of Woes',
          duration: '۵۵ دقیقه',
          description: 'قتل‌های زنجیره‌ای به اوج می‌رسند.',
          thumbnail: '/saintstream/posters/wednesday.jpg',
        },
      ],
    },
    {
      id: 2,
      title: 'فصل ۲',
      episodes: [
        {
          id: 1,
          title: 'قسمت ۱ — بازگشت به نِورمور',
          duration: '۵۰ دقیقه',
          description: 'ونزدی با تهدید تازه‌ای به مدرسه بازمی‌گردد.',
          thumbnail: '/saintstream/posters/wednesday.jpg',
        },
        {
          id: 2,
          title: 'قسمت ۲ — سایه‌های خوابگاه',
          duration: '۴۹ دقیقه',
          description: 'خوابگاه رازهایی از گذشته فاش می‌کند.',
          thumbnail: '/saintstream/posters/wednesday.jpg',
        },
        {
          id: 3,
          title: 'قسمت ۳ — رقص شبانه',
          duration: '۵۱ دقیقه',
          description: 'رویداد اجتماعی نقاب‌ها را کنار می‌زند.',
          thumbnail: '/saintstream/hero/wednesday.jpg',
        },
        {
          id: 4,
          title: 'قسمت ۴ — کتاب نفرین‌شده',
          duration: '۵۰ دقیقه',
          description: 'کتابی قدیمی مسیر تحقیق را عوض می‌کند.',
          thumbnail: '/saintstream/posters/wednesday.jpg',
        },
        {
          id: 5,
          title: 'قسمت ۵ — پیوند خون',
          duration: '۵۲ دقیقه',
          description: 'پیوند خونی قدرت تازه‌ای آزاد می‌کند.',
          thumbnail: '/saintstream/posters/wednesday.jpg',
        },
        {
          id: 6,
          title: 'قسمت ۶ — شکارچی جنگل',
          duration: '۵۱ دقیقه',
          description: 'شکار در جنگل به دام تبدیل می‌شود.',
          thumbnail: '/saintstream/hero/wednesday.jpg',
        },
        {
          id: 7,
          title: 'قسمت ۷ — نقاب دروغ',
          duration: '۵۳ دقیقه',
          description: 'هویت جعلی یکی از شخصیت‌ها افشا می‌شود.',
          thumbnail: '/saintstream/posters/wednesday.jpg',
        },
        {
          id: 8,
          title: 'قسمت ۸ — شب پایانی نِورمور',
          duration: '۵۸ دقیقه',
          description: 'نبرد نهایی فصل در نِورمور رقم می‌خورد.',
          thumbnail: '/saintstream/posters/wednesday.jpg',
        },
      ],
    },
  ],
  'shogun': [
    {
      id: 1,
      title: 'فصل ۱',
      episodes: [
        {
          id: 1,
          title: 'Anjin',
          duration: '۵۶ دقیقه',
          description: 'جان بلک‌ثورن وارد ژاپن فئودالی می‌شود.',
          thumbnail: '/saintstream/posters/shogun.jpg',
        },
        {
          id: 2,
          title: 'Servants of Two Masters',
          duration: '۵۴ دقیقه',
          description: 'خدمت به دو ارباب وفاداری را می‌آزماید.',
          thumbnail: '/saintstream/posters/shogun.jpg',
        },
        {
          id: 3,
          title: 'Tomorrow Is Tomorrow',
          duration: '۵۲ دقیقه',
          description: 'فردا وعده‌ای است که شاید نرسد.',
          thumbnail: '/saintstream/hero/shogun.jpg',
        },
        {
          id: 4,
          title: 'The Eightfold Fence',
          duration: '۵۵ دقیقه',
          description: 'دیوار هشت‌لایه قدرت را محافظت می‌کند.',
          thumbnail: '/saintstream/posters/shogun.jpg',
        },
        {
          id: 5,
          title: 'Broken to the Fist',
          duration: '۵۳ دقیقه',
          description: 'شکست جسمی راهی به سوی درک فرهنگ است.',
          thumbnail: '/saintstream/posters/shogun.jpg',
        },
        {
          id: 6,
          title: 'Artists of the Floating World',
          duration: '۵۸ دقیقه',
          description: 'هنرمندان جهان شناور سیاست را بازمی‌تابانند.',
          thumbnail: '/saintstream/hero/shogun.jpg',
        },
        {
          id: 7,
          title: 'A Stick of Time',
          duration: '۵۱ دقیقه',
          description: 'زمان مثل چوبی شکننده می‌شکند.',
          thumbnail: '/saintstream/posters/shogun.jpg',
        },
        {
          id: 8,
          title: 'The Abyss of Life',
          duration: '۵۷ دقیقه',
          description: 'مغاک زندگی شخصیت‌ها را می‌بلعد.',
          thumbnail: '/saintstream/posters/shogun.jpg',
        },
        {
          id: 9,
          title: 'Crimson Sky',
          duration: '۶۰ دقیقه',
          description: 'آسمان سرخ خبر از جنگ می‌دهد.',
          thumbnail: '/saintstream/hero/shogun.jpg',
        },
        {
          id: 10,
          title: 'A Dream of a Dream',
          duration: '۷۰ دقیقه',
          description: 'رؤیای درون رؤیا سرنوشت شوگان را می‌بندد.',
          thumbnail: '/saintstream/posters/shogun.jpg',
        },
      ],
    },
  ],
  'arcane': [
    {
      id: 1,
      title: 'فصل ۱',
      episodes: [
        {
          id: 1,
          title: 'Welcome to the Playground',
          duration: '۴۳ دقیقه',
          description: 'خواهران در زاوندل وارد دنیای خشن زیرشهر می‌شوند.',
          thumbnail: '/saintstream/posters/arcane.jpg',
        },
        {
          id: 2,
          title: 'Some Mysteries Are Better Left Unsolved',
          duration: '۴۰ دقیقه',
          description: 'رمز و رازهای علمی بهای سنگینی دارند.',
          thumbnail: '/saintstream/posters/arcane.jpg',
        },
        {
          id: 3,
          title: 'The Base Violence Necessary for Change',
          duration: '۴۴ دقیقه',
          description: 'خشونت پایه تغییر اجتماعی می‌شود.',
          thumbnail: '/saintstream/hero/arcane.jpg',
        },
        {
          id: 4,
          title: 'Happy Progress Day!',
          duration: '۴۲ دقیقه',
          description: 'روز پیشرفت نقاب نابرابری را کنار می‌زند.',
          thumbnail: '/saintstream/posters/arcane.jpg',
        },
        {
          id: 5,
          title: 'Everybody Wants to Be My Enemy',
          duration: '۴۰ دقیقه',
          description: 'دشمنی شخصی جنگ بزرگ‌تری می‌سازد.',
          thumbnail: '/saintstream/posters/arcane.jpg',
        },
        {
          id: 6,
          title: 'When These Walls Come Tumbling Down',
          duration: '۴۲ دقیقه',
          description: 'دیوارها فرومی‌ریزند و اتحادها می‌شکنند.',
          thumbnail: '/saintstream/hero/arcane.jpg',
        },
        {
          id: 7,
          title: 'The Boy Savior',
          duration: '۴۱ دقیقه',
          description: 'پسر نجات‌دهنده قربانی جاه‌طلبی می‌شود.',
          thumbnail: '/saintstream/posters/arcane.jpg',
        },
        {
          id: 8,
          title: 'Oil and Water',
          duration: '۴۱ دقیقه',
          description: 'نفت و آب؛ دو جهان که مخلوط نمی‌شوند.',
          thumbnail: '/saintstream/posters/arcane.jpg',
        },
        {
          id: 9,
          title: 'The Monster You Created',
          duration: '۴۵ دقیقه',
          description: 'هیولایی که خود ساخته‌اند بازمی‌گردد.',
          thumbnail: '/saintstream/hero/arcane.jpg',
        },
      ],
    },
    {
      id: 2,
      title: 'فصل ۲',
      episodes: [
        {
          id: 1,
          title: 'Heavy Is the Crown',
          duration: '۴۰ دقیقه',
          description: 'تاج سنگین مسئولیت را خرد می‌کند.',
          thumbnail: '/saintstream/posters/arcane.jpg',
        },
        {
          id: 2,
          title: 'Watch It All Burn',
          duration: '۴۲ دقیقه',
          description: 'همه‌چیز در آتش جاه‌طلبی می‌سوزد.',
          thumbnail: '/saintstream/posters/arcane.jpg',
        },
        {
          id: 3,
          title: 'Finally Got the Name Right',
          duration: '۴۱ دقیقه',
          description: 'نام درست بالاخره گفته می‌شود.',
          thumbnail: '/saintstream/hero/arcane.jpg',
        },
        {
          id: 4,
          title: 'Paint the Town Blue',
          duration: '۴۳ دقیقه',
          description: 'شهر به رنگ آبی خشم درمی‌آید.',
          thumbnail: '/saintstream/posters/arcane.jpg',
        },
        {
          id: 5,
          title: 'Blisters and Bedrock',
          duration: '۴۰ دقیقه',
          description: 'زخم و سنگ‌بستر هویت را می‌سازند.',
          thumbnail: '/saintstream/posters/arcane.jpg',
        },
        {
          id: 6,
          title: 'The Message Hidden Within the Pattern',
          duration: '۴۲ دقیقه',
          description: 'پیام پنهان در الگو فاش می‌شود.',
          thumbnail: '/saintstream/hero/arcane.jpg',
        },
        {
          id: 7,
          title: 'Pretend Like It\'s the First Time',
          duration: '۴۴ دقیقه',
          description: 'وانمود به شروع دوباره سخت‌تر از جنگ است.',
          thumbnail: '/saintstream/posters/arcane.jpg',
        },
        {
          id: 8,
          title: 'Killing Is a Cycle',
          duration: '۴۳ دقیقه',
          description: 'کشتن چرخه‌ای بی‌پایان است.',
          thumbnail: '/saintstream/posters/arcane.jpg',
        },
        {
          id: 9,
          title: 'The Dirt Under Your Nails',
          duration: '۴۵ دقیقه',
          description: 'خاک زیر ناخن یادآور ریشه است.',
          thumbnail: '/saintstream/hero/arcane.jpg',
        },
      ],
    },
  ],
  'witcher': [
    {
      id: 1,
      title: 'فصل ۱',
      episodes: [
        {
          id: 1,
          title: 'The End\'s Beginning',
          duration: '۶۱ دقیقه',
          description: 'آغاز پایان برای گرالت و سیره‌ای تازه.',
          thumbnail: '/saintstream/posters/witcher.jpg',
        },
        {
          id: 2,
          title: 'Four Marks',
          duration: '۶۱ دقیقه',
          description: 'چهار مارک مسیر سرنوشت را عوض می‌کند.',
          thumbnail: '/saintstream/posters/witcher.jpg',
        },
        {
          id: 3,
          title: 'Betrayer Moon',
          duration: '۶۰ دقیقه',
          description: 'ماه خیانت هیولا و انسان را درهم می‌آمیزد.',
          thumbnail: '/saintstream/hero/witcher.jpg',
        },
        {
          id: 4,
          title: 'Of Banquets, Bastards and Burials',
          duration: '۶۲ دقیقه',
          description: 'ضیافت، حرام‌زاده و خاکسپاری.',
          thumbnail: '/saintstream/posters/witcher.jpg',
        },
        {
          id: 5,
          title: 'Bottled Appetites',
          duration: '۵۹ دقیقه',
          description: 'هوس‌های بطری‌شده جادو آزاد می‌کنند.',
          thumbnail: '/saintstream/posters/witcher.jpg',
        },
        {
          id: 6,
          title: 'Rare Species',
          duration: '۶۰ دقیقه',
          description: 'گونه‌ای نادر شکار بزرگ می‌سازد.',
          thumbnail: '/saintstream/hero/witcher.jpg',
        },
        {
          id: 7,
          title: 'Before a Fall',
          duration: '۵۷ دقیقه',
          description: 'پیش از سقوط، غرور اوج می‌گیرد.',
          thumbnail: '/saintstream/posters/witcher.jpg',
        },
        {
          id: 8,
          title: 'Much More',
          duration: '۶۷ دقیقه',
          description: 'پیوند تقدیر بسیار فراتر می‌رود.',
          thumbnail: '/saintstream/posters/witcher.jpg',
        },
      ],
    },
    {
      id: 2,
      title: 'فصل ۲',
      episodes: [
        {
          id: 1,
          title: 'A Grain of Truth',
          duration: '۵۸ دقیقه',
          description: 'دانه‌ای از حقیقت در افسانه پنهان است.',
          thumbnail: '/saintstream/posters/witcher.jpg',
        },
        {
          id: 2,
          title: 'Kaer Morhen',
          duration: '۵۹ دقیقه',
          description: 'بازگشت به کائِر مورهِن پناهگاهی متزلزل است.',
          thumbnail: '/saintstream/posters/witcher.jpg',
        },
        {
          id: 3,
          title: 'What Is Lost',
          duration: '۵۶ دقیقه',
          description: 'آنچه از دست رفته باز نمی‌گردد.',
          thumbnail: '/saintstream/hero/witcher.jpg',
        },
        {
          id: 4,
          title: 'Redanian Intelligence',
          duration: '۵۵ دقیقه',
          description: 'جاسوسی ردانیا توطئه می‌چیند.',
          thumbnail: '/saintstream/posters/witcher.jpg',
        },
        {
          id: 5,
          title: 'Turn Your Back',
          duration: '۵۷ دقیقه',
          description: 'پشت کردن به گذشته بهای سنگینی دارد.',
          thumbnail: '/saintstream/posters/witcher.jpg',
        },
        {
          id: 6,
          title: 'Dear Friend...',
          duration: '۵۸ دقیقه',
          description: 'نامه‌ای به دوست قدیمی زخم کهنه را باز می‌کند.',
          thumbnail: '/saintstream/hero/witcher.jpg',
        },
        {
          id: 7,
          title: 'Voleth Meir',
          duration: '۶۰ دقیقه',
          description: 'ولِث مِیر تاریکی را بیدار می‌کند.',
          thumbnail: '/saintstream/posters/witcher.jpg',
        },
        {
          id: 8,
          title: 'Family',
          duration: '۶۴ دقیقه',
          description: 'خانواده معنای تازه‌ای در جنگ پیدا می‌کند.',
          thumbnail: '/saintstream/posters/witcher.jpg',
        },
      ],
    },
    {
      id: 3,
      title: 'فصل ۳',
      episodes: [
        {
          id: 1,
          title: 'Shaerrawedd',
          duration: '۵۸ دقیقه',
          description: 'ویرانه‌های شایرراوِد خاطره زنده می‌کنند.',
          thumbnail: '/saintstream/posters/witcher.jpg',
        },
        {
          id: 2,
          title: 'Unbound',
          duration: '۵۷ دقیقه',
          description: 'بندها گسسته می‌شوند و قدرت رها می‌گردد.',
          thumbnail: '/saintstream/posters/witcher.jpg',
        },
        {
          id: 3,
          title: 'Reunion',
          duration: '۵۶ دقیقه',
          description: 'بازگشت دوستان با خیانت همراه است.',
          thumbnail: '/saintstream/hero/witcher.jpg',
        },
        {
          id: 4,
          title: 'The Art of Illusion',
          duration: '۵۵ دقیقه',
          description: 'هنر توهم واقعیت را می‌پوشاند.',
          thumbnail: '/saintstream/posters/witcher.jpg',
        },
        {
          id: 5,
          title: 'A Sword Without a Hilt',
          duration: '۵۸ دقیقه',
          description: 'شمشیر بی‌قبضه خطرناک‌تر است.',
          thumbnail: '/saintstream/posters/witcher.jpg',
        },
        {
          id: 6,
          title: 'Everybody Has a Plan...',
          duration: '۵۹ دقیقه',
          description: 'هر کس نقشه‌ای دارد تا وقتی اوضاع به هم بریزد.',
          thumbnail: '/saintstream/hero/witcher.jpg',
        },
        {
          id: 7,
          title: 'Out of the Fire, Into the Frying Pan',
          duration: '۶۰ دقیقه',
          description: 'از آتش به تابه؛ فرار بی‌پایان.',
          thumbnail: '/saintstream/posters/witcher.jpg',
        },
        {
          id: 8,
          title: 'The Cost of Chaos',
          duration: '۶۵ دقیقه',
          description: 'بهای آشوب از همه گرفته می‌شود.',
          thumbnail: '/saintstream/posters/witcher.jpg',
        },
      ],
    },
  ],
  'squid-game': [
    {
      id: 1,
      title: 'فصل ۱',
      episodes: [
        {
          id: 1,
          title: 'Red Light, Green Light',
          duration: '۶۰ دقیقه',
          description: 'بازی چراغ قرمز چراغ سبز آغاز جهنم است.',
          thumbnail: '/saintstream/posters/squid-game.jpg',
        },
        {
          id: 2,
          title: 'Hell',
          duration: '۶۳ دقیقه',
          description: 'جهنم قوانین خودش را دارد.',
          thumbnail: '/saintstream/posters/squid-game.jpg',
        },
        {
          id: 3,
          title: 'The Man with the Umbrella',
          duration: '۵۶ دقیقه',
          description: 'مرد چتردار راز بازی را نزدیک می‌کند.',
          thumbnail: '/saintstream/hero/squid-game.jpg',
        },
        {
          id: 4,
          title: 'Stick to the Team',
          duration: '۵۵ دقیقه',
          description: 'وفاداری به تیم تنها راه بقاست.',
          thumbnail: '/saintstream/posters/squid-game.jpg',
        },
        {
          id: 5,
          title: 'A Fair World',
          duration: '۵۲ دقیقه',
          description: 'جهانی عادلانه فقط روی کاغذ وجود دارد.',
          thumbnail: '/saintstream/posters/squid-game.jpg',
        },
        {
          id: 6,
          title: 'Gganbu',
          duration: '۶۲ دقیقه',
          description: 'دوستی در بازی به آزمون مرگبار تبدیل می‌شود.',
          thumbnail: '/saintstream/hero/squid-game.jpg',
        },
        {
          id: 7,
          title: 'VIPS',
          duration: '۵۸ دقیقه',
          description: 'مهمانان وی‌آی‌پی تماشای رنج را جشن می‌گیرند.',
          thumbnail: '/saintstream/posters/squid-game.jpg',
        },
        {
          id: 8,
          title: 'Front Man',
          duration: '۳۳ دقیقه',
          description: 'هویت فرانت‌من پرده از سیستم برمی‌دارد.',
          thumbnail: '/saintstream/posters/squid-game.jpg',
        },
        {
          id: 9,
          title: 'One Lucky Day',
          duration: '۵۶ دقیقه',
          description: 'یک روز خوش‌شانسی پایان فصل را می‌سازد.',
          thumbnail: '/saintstream/hero/squid-game.jpg',
        },
      ],
    },
    {
      id: 2,
      title: 'فصل ۲',
      episodes: [
        {
          id: 1,
          title: 'Bread and Lottery',
          duration: '۶۰ دقیقه',
          description: 'نان و بخت‌آزمایی مردم را فریب می‌دهد.',
          thumbnail: '/saintstream/posters/squid-game.jpg',
        },
        {
          id: 2,
          title: 'Halloween Party',
          duration: '۵۲ دقیقه',
          description: 'مهمانی هالووین نقاب تازه‌ای می‌سازد.',
          thumbnail: '/saintstream/posters/squid-game.jpg',
        },
        {
          id: 3,
          title: '001',
          duration: '۵۸ دقیقه',
          description: 'شماره ۰۰۱ راز بازی تازه است.',
          thumbnail: '/saintstream/hero/squid-game.jpg',
        },
        {
          id: 4,
          title: 'Six Legs',
          duration: '۵۵ دقیقه',
          description: 'شش پا برای یک بدن؛ اتحاد اجباری.',
          thumbnail: '/saintstream/posters/squid-game.jpg',
        },
        {
          id: 5,
          title: 'The New World Order',
          duration: '۵۴ دقیقه',
          description: 'نظم نوین جهانی بازی را بازتعریف می‌کند.',
          thumbnail: '/saintstream/posters/squid-game.jpg',
        },
        {
          id: 6,
          title: 'The Door Opens',
          duration: '۵۶ دقیقه',
          description: 'در باز می‌شود و انتخاب اجباری می‌آید.',
          thumbnail: '/saintstream/hero/squid-game.jpg',
        },
        {
          id: 7,
          title: 'Friend or Foe',
          duration: '۶۰ دقیقه',
          description: 'دوست یا دشمن؛ خط باریک بقا.',
          thumbnail: '/saintstream/posters/squid-game.jpg',
        },
      ],
    },
  ],
  'the-last-of-us': [
    {
      id: 1,
      title: 'فصل ۱',
      episodes: [
        {
          id: 1,
          title: 'When You\'re Lost in the Darkness',
          duration: '۸۱ دقیقه',
          description: 'در تاریکی گم‌شده، جوئل و الی مسیرشان را آغاز می‌کنند.',
          thumbnail: '/saintstream/posters/the-last-of-us.jpg',
        },
        {
          id: 2,
          title: 'Infected',
          duration: '۵۴ دقیقه',
          description: 'آلوده‌ها قوانین بقا را تحمیل می‌کنند.',
          thumbnail: '/saintstream/posters/the-last-of-us.jpg',
        },
        {
          id: 3,
          title: 'Long, Long Time',
          duration: '۷۶ دقیقه',
          description: 'داستان بیل و فرانک معنای عشق در آخرالزمان است.',
          thumbnail: '/saintstream/hero/the-last-of-us.jpg',
        },
        {
          id: 4,
          title: 'Please Hold to My Hand',
          duration: '۴۶ دقیقه',
          description: 'دست در دست، از خطر عبور می‌کنند.',
          thumbnail: '/saintstream/posters/the-last-of-us.jpg',
        },
        {
          id: 5,
          title: 'Endure and Survive',
          duration: '۵۹ دقیقه',
          description: 'تحمل و بقا شعار روزهای سخت است.',
          thumbnail: '/saintstream/posters/the-last-of-us.jpg',
        },
        {
          id: 6,
          title: 'Kin',
          duration: '۵۹ دقیقه',
          description: 'خویشاوندی فراتر از خون معنا پیدا می‌کند.',
          thumbnail: '/saintstream/hero/the-last-of-us.jpg',
        },
        {
          id: 7,
          title: 'Left Behind',
          duration: '۵۷ دقیقه',
          description: 'بازگشت به گذشتهٔ الی زخم کهنه را باز می‌کند.',
          thumbnail: '/saintstream/posters/the-last-of-us.jpg',
        },
        {
          id: 8,
          title: 'When We Are in Need',
          duration: '۵۱ دقیقه',
          description: 'در نیاز، ایمان و خشونت درهم می‌آمیزند.',
          thumbnail: '/saintstream/posters/the-last-of-us.jpg',
        },
        {
          id: 9,
          title: 'Look for the Light',
          duration: '۷۵ دقیقه',
          description: 'جست‌وجوی نور در پایان مسیر بیمارستانی.',
          thumbnail: '/saintstream/hero/the-last-of-us.jpg',
        },
      ],
    },
    {
      id: 2,
      title: 'فصل ۲',
      episodes: [
        {
          id: 1,
          title: 'Future Days',
          duration: '۵۸ دقیقه',
          description: 'روزهای آینده آرامشی شکننده دارند.',
          thumbnail: '/saintstream/posters/the-last-of-us.jpg',
        },
        {
          id: 2,
          title: 'Through the Valley',
          duration: '۶۶ دقیقه',
          description: 'عبور از دره بهای سنگینی می‌طلبد.',
          thumbnail: '/saintstream/posters/the-last-of-us.jpg',
        },
        {
          id: 3,
          title: 'Path',
          duration: '۵۵ دقیقه',
          description: 'مسیر انتقام از سیاتل می‌گذرد.',
          thumbnail: '/saintstream/hero/the-last-of-us.jpg',
        },
        {
          id: 4,
          title: 'Day One',
          duration: '۶۰ دقیقه',
          description: 'روز اول در شهر ویران پر از تهدید است.',
          thumbnail: '/saintstream/posters/the-last-of-us.jpg',
        },
        {
          id: 5,
          title: 'Feel Her Love',
          duration: '۵۸ دقیقه',
          description: 'عشق و نفرت در هم می‌تنند.',
          thumbnail: '/saintstream/posters/the-last-of-us.jpg',
        },
        {
          id: 6,
          title: 'The Price',
          duration: '۶۲ دقیقه',
          description: 'بهای انتخاب‌ها روشن می‌شود.',
          thumbnail: '/saintstream/hero/the-last-of-us.jpg',
        },
        {
          id: 7,
          title: 'Convergence',
          duration: '۷۰ دقیقه',
          description: 'راه‌ها در نقطهٔ برخورد به هم می‌رسند.',
          thumbnail: '/saintstream/posters/the-last-of-us.jpg',
        },
      ],
    },
  ],
  'weak-hero': [
    {
      id: 1,
      title: 'فصل ۱',
      episodes: [
        {
          id: 1,
          title: 'قسمت ۱ — تازه‌وارد',
          duration: '۴۰ دقیقه',
          description: 'تازه‌واردی وارد دبیرستان خشن می‌شود.',
          thumbnail: '/saintstream/posters/weak-hero.jpg',
        },
        {
          id: 2,
          title: 'قسمت ۲ — اتحاد ضعیف‌ها',
          duration: '۳۸ دقیقه',
          description: 'اتحاد شکننده میان دانش‌آموزان شکل می‌گیرد.',
          thumbnail: '/saintstream/posters/weak-hero.jpg',
        },
        {
          id: 3,
          title: 'قسمت ۳ — قوانین راهرو',
          duration: '۳۹ دقیقه',
          description: 'قلدرها قوانین نانوشته را تحمیل می‌کنند.',
          thumbnail: '/saintstream/hero/weak-hero.jpg',
        },
        {
          id: 4,
          title: 'قسمت ۴ — مشت اول',
          duration: '۴۰ دقیقه',
          description: 'اولین نبرد جدی در مدرسه رخ می‌دهد.',
          thumbnail: '/saintstream/posters/weak-hero.jpg',
        },
        {
          id: 5,
          title: 'قسمت ۵ — قدرت پنهان',
          duration: '۴۱ دقیقه',
          description: 'راز قدرت یکی از دانش‌آموزان فاش می‌شود.',
          thumbnail: '/saintstream/posters/weak-hero.jpg',
        },
        {
          id: 6,
          title: 'قسمت ۶ — شکاف',
          duration: '۴۰ دقیقه',
          description: 'خیانت درون گروه شکاف ایجاد می‌کند.',
          thumbnail: '/saintstream/hero/weak-hero.jpg',
        },
        {
          id: 7,
          title: 'قسمت ۷ — پیش از طوفان',
          duration: '۴۲ دقیقه',
          description: 'رویارویی نهایی نزدیک می‌شود.',
          thumbnail: '/saintstream/posters/weak-hero.jpg',
        },
        {
          id: 8,
          title: 'قسمت ۸ — ضربه آخر',
          duration: '۴۵ دقیقه',
          description: 'آخرین ضربه سرنوشت مدرسه را عوض می‌کند.',
          thumbnail: '/saintstream/posters/weak-hero.jpg',
        },
      ],
    },
  ],
  'beef': [
    {
      id: 1,
      title: 'فصل ۱',
      episodes: [
        {
          id: 1,
          title: 'The Birds of Paradise',
          duration: '۳۷ دقیقه',
          description: 'یک تصادف جاده‌ای دو زندگی را به هم گره می‌زند.',
          thumbnail: '/saintstream/posters/beef.jpg',
        },
        {
          id: 2,
          title: 'The Ratchet Effect',
          duration: '۳۶ دقیقه',
          description: 'اثر جغجغه‌ای خشم را غیرقابل بازگشت می‌کند.',
          thumbnail: '/saintstream/posters/beef.jpg',
        },
        {
          id: 3,
          title: 'I Am a Bird Now',
          duration: '۳۵ دقیقه',
          description: 'هویت و خشم جای هم را می‌گیرند.',
          thumbnail: '/saintstream/hero/beef.jpg',
        },
        {
          id: 4,
          title: 'I Gotta Be Me',
          duration: '۳۶ دقیقه',
          description: 'هر کس سعی می‌کند خودش باشد و شکست می‌خورد.',
          thumbnail: '/saintstream/posters/beef.jpg',
        },
        {
          id: 5,
          title: 'Feelings',
          duration: '۳۴ دقیقه',
          description: 'احساسات سرکوب‌شده منفجر می‌شوند.',
          thumbnail: '/saintstream/posters/beef.jpg',
        },
        {
          id: 6,
          title: 'Bistro',
          duration: '۳۸ دقیقه',
          description: 'رستوران صحنهٔ تقابل طبقاتی می‌شود.',
          thumbnail: '/saintstream/hero/beef.jpg',
        },
        {
          id: 7,
          title: 'I Think I Wanna Be Religious',
          duration: '۳۵ دقیقه',
          description: 'جست‌وجوی معنا به مسیر خطرناک می‌رود.',
          thumbnail: '/saintstream/posters/beef.jpg',
        },
        {
          id: 8,
          title: 'The Drama of Original Life',
          duration: '۳۶ دقیقه',
          description: 'درام زندگی اصلی به سطح می‌آید.',
          thumbnail: '/saintstream/posters/beef.jpg',
        },
        {
          id: 9,
          title: 'The Fantasy of My Life',
          duration: '۳۷ دقیقه',
          description: 'فانتزی زندگی با واقعیت برخورد می‌کند.',
          thumbnail: '/saintstream/hero/beef.jpg',
        },
        {
          id: 10,
          title: 'Figures of Speech',
          duration: '۴۰ دقیقه',
          description: 'استعاره‌ها به خشونت واقعی تبدیل می‌شوند.',
          thumbnail: '/saintstream/posters/beef.jpg',
        },
      ],
    },
  ],
  'valhalla-murders': [
    {
      id: 1,
      title: 'فصل ۱',
      episodes: [
        {
          id: 1,
          title: 'قسمت ۱ — جسد در دره',
          duration: '۴۵ دقیقه',
          description: 'کشف جسد در ایسلند پرونده‌ای کهنه را زنده می‌کند.',
          thumbnail: '/saintstream/posters/valhalla-murders.jpg',
        },
        {
          id: 2,
          title: 'قسمت ۲ — دو کارآگاه',
          duration: '۴۴ دقیقه',
          description: 'همکاری پلیس ایسلند و نروژ آغاز می‌شود.',
          thumbnail: '/saintstream/posters/valhalla-murders.jpg',
        },
        {
          id: 3,
          title: 'قسمت ۳ — ردپا در برف',
          duration: '۴۶ دقیقه',
          description: 'ردپا در برف به گذشته تاریک می‌رسد.',
          thumbnail: '/saintstream/hero/valhalla-murders.jpg',
        },
        {
          id: 4,
          title: 'قسمت ۴ — باشگاه قدیمی',
          duration: '۴۵ دقیقه',
          description: 'باشگاه جوانان رازهای خونین دارد.',
          thumbnail: '/saintstream/posters/valhalla-murders.jpg',
        },
        {
          id: 5,
          title: 'قسمت ۵ — شاهد خاموش',
          duration: '۴۷ دقیقه',
          description: 'شاهدی که حرف نمی‌زند کلید پرونده است.',
          thumbnail: '/saintstream/posters/valhalla-murders.jpg',
        },
        {
          id: 6,
          title: 'قسمت ۶ — دروغ خانوادگی',
          duration: '۴۶ دقیقه',
          description: 'دروغ‌های خانوادگی پرده از قاتل برمی‌دارند.',
          thumbnail: '/saintstream/hero/valhalla-murders.jpg',
        },
        {
          id: 7,
          title: 'قسمت ۷ — شکار در تاریکی',
          duration: '۴۸ دقیقه',
          description: 'شکار قاتل در شب قطبی شدت می‌گیرد.',
          thumbnail: '/saintstream/posters/valhalla-murders.jpg',
        },
        {
          id: 8,
          title: 'قسمت ۸ — عدالت سرد',
          duration: '۵۰ دقیقه',
          description: 'عدالت در سرمای شمال به پایان می‌رسد.',
          thumbnail: '/saintstream/posters/valhalla-murders.jpg',
        },
      ],
    },
  ],
  'insider': [
    {
      id: 1,
      title: 'فصل ۱',
      episodes: [
        {
          id: 1,
          title: 'قسمت ۱ — نفوذ',
          duration: '۶۵ دقیقه',
          description: 'مامور مخفی وارد شبکه فساد زندان می‌شود.',
          thumbnail: '/saintstream/posters/insider.jpg',
        },
        {
          id: 2,
          title: 'قسمت ۲ — سلسله مراتب',
          duration: '۶۲ دقیقه',
          description: 'سلسله‌مراتب زندان قوانین نانوشته دارد.',
          thumbnail: '/saintstream/posters/insider.jpg',
        },
        {
          id: 3,
          title: 'قسمت ۳ — معامله',
          duration: '۶۴ دقیقه',
          description: 'معامله‌ای خطرناک میان باندها شکل می‌گیرد.',
          thumbnail: '/saintstream/hero/insider.jpg',
        },
        {
          id: 4,
          title: 'قسمت ۴ — شاهد',
          duration: '۶۳ دقیقه',
          description: 'شاهدی کلیدی ناپدید می‌شود.',
          thumbnail: '/saintstream/posters/insider.jpg',
        },
        {
          id: 5,
          title: 'قسمت ۵ — فشار',
          duration: '۶۵ دقیقه',
          description: 'فشار از بیرون عملیات را تهدید می‌کند.',
          thumbnail: '/saintstream/posters/insider.jpg',
        },
        {
          id: 6,
          title: 'قسمت ۶ — خیانت',
          duration: '۶۲ دقیقه',
          description: 'خیانت از جایی که انتظارش نمی‌رفت.',
          thumbnail: '/saintstream/hero/insider.jpg',
        },
        {
          id: 7,
          title: 'قسمت ۷ — مدارک',
          duration: '۶۴ دقیقه',
          description: 'مدارک جعلی حقیقت را می‌پوشاند.',
          thumbnail: '/saintstream/posters/insider.jpg',
        },
        {
          id: 8,
          title: 'قسمت ۸ — شورش',
          duration: '۶۶ دقیقه',
          description: 'شورش کنترل زندان را به هم می‌ریزد.',
          thumbnail: '/saintstream/posters/insider.jpg',
        },
        {
          id: 9,
          title: 'قسمت ۹ — بازگشت',
          duration: '۶۳ دقیقه',
          description: 'بازگشتی غیرمنتظره نقشه را عوض می‌کند.',
          thumbnail: '/saintstream/hero/insider.jpg',
        },
        {
          id: 10,
          title: 'قسمت ۱۰ — دام',
          duration: '۶۵ دقیقه',
          description: 'دامی برای نفوذی چیده می‌شود.',
          thumbnail: '/saintstream/posters/insider.jpg',
        },
        {
          id: 11,
          title: 'قسمت ۱۱ — افشا',
          duration: '۶۴ دقیقه',
          description: 'افشای بخشی از توطئه همه را می‌لرزاند.',
          thumbnail: '/saintstream/posters/insider.jpg',
        },
        {
          id: 12,
          title: 'قسمت ۱۲ — قربانی',
          duration: '۶۶ دقیقه',
          description: 'قربانی تازه‌ای بهای حقیقت می‌شود.',
          thumbnail: '/saintstream/hero/insider.jpg',
        },
        {
          id: 13,
          title: 'قسمت ۱۳ — اتحاد',
          duration: '۶۵ دقیقه',
          description: 'اتحاد شکننده میان دشمنان سابق.',
          thumbnail: '/saintstream/posters/insider.jpg',
        },
        {
          id: 14,
          title: 'قسمت ۱۴ — سقوط',
          duration: '۶۷ دقیقه',
          description: 'سقوط یکی از ستون‌های قدرت.',
          thumbnail: '/saintstream/posters/insider.jpg',
        },
        {
          id: 15,
          title: 'قسمت ۱۵ — ضدحمله',
          duration: '۶۸ دقیقه',
          description: 'ضدحمله نهایی آغاز می‌شود.',
          thumbnail: '/saintstream/hero/insider.jpg',
        },
        {
          id: 16,
          title: 'قسمت ۱۶ — حسابرسی',
          duration: '۷۰ دقیقه',
          description: 'حسابرسی خونین پرونده را می‌بندد.',
          thumbnail: '/saintstream/posters/insider.jpg',
        },
      ],
    },
  ],
  'race': [
    {
      id: 1,
      title: 'فصل ۱',
      episodes: [
        {
          id: 1,
          title: 'قسمت ۱ — خط شروع',
          duration: '۵۵ دقیقه',
          description: 'رقابت برای ورود به صنعت سرگرمی آغاز می‌شود.',
          thumbnail: '/saintstream/posters/race.jpg',
        },
        {
          id: 2,
          title: 'قسمت ۲ — آزمون اول',
          duration: '۵۲ دقیقه',
          description: 'اولین آزمون استعدادها را جدا می‌کند.',
          thumbnail: '/saintstream/posters/race.jpg',
        },
        {
          id: 3,
          title: 'قسمت ۳ — دوربین',
          duration: '۵۴ دقیقه',
          description: 'دوربین نقاب شخصیت‌ها را برمی‌دارد.',
          thumbnail: '/saintstream/hero/race.jpg',
        },
        {
          id: 4,
          title: 'قسمت ۴ — شایعه',
          duration: '۵۳ دقیقه',
          description: 'شایعه مسیر یک شرکت‌کننده را عوض می‌کند.',
          thumbnail: '/saintstream/posters/race.jpg',
        },
        {
          id: 5,
          title: 'قسمت ۵ — تیم',
          duration: '۵۵ دقیقه',
          description: 'تشکیل تیم همکاری و رقابت را درهم می‌آمیزد.',
          thumbnail: '/saintstream/posters/race.jpg',
        },
        {
          id: 6,
          title: 'قسمت ۶ — شکست',
          duration: '۵۲ دقیقه',
          description: 'شکست تلخ انگیزه تازه‌ای می‌سازد.',
          thumbnail: '/saintstream/hero/race.jpg',
        },
        {
          id: 7,
          title: 'قسمت ۷ — بازگشت',
          duration: '۵۴ دقیقه',
          description: 'بازگشت قوی‌تر پس از حذف موقت.',
          thumbnail: '/saintstream/posters/race.jpg',
        },
        {
          id: 8,
          title: 'قسمت ۸ — فینال نیمه',
          duration: '۵۶ دقیقه',
          description: 'نیمه‌نهایی فشار را به اوج می‌رساند.',
          thumbnail: '/saintstream/posters/race.jpg',
        },
        {
          id: 9,
          title: 'قسمت ۹ — افشاگری',
          duration: '۵۵ دقیقه',
          description: 'افشاگری پشت صحنه همه را شوکه می‌کند.',
          thumbnail: '/saintstream/hero/race.jpg',
        },
        {
          id: 10,
          title: 'قسمت ۱۰ — انتخاب',
          duration: '۵۷ دقیقه',
          description: 'انتخاب داوران سرنوشت‌ساز است.',
          thumbnail: '/saintstream/posters/race.jpg',
        },
        {
          id: 11,
          title: 'قسمت ۱۱ — آخرین شانس',
          duration: '۵۶ دقیقه',
          description: 'آخرین شانس برای درخشش.',
          thumbnail: '/saintstream/posters/race.jpg',
        },
        {
          id: 12,
          title: 'قسمت ۱۲ — قهرمان',
          duration: '۶۰ دقیقه',
          description: 'قهرمان فصل روی صحنه اعلام می‌شود.',
          thumbnail: '/saintstream/hero/race.jpg',
        },
      ],
    },
  ],
  'ghost-doctor': [
    {
      id: 1,
      title: 'فصل ۱',
      episodes: [
        {
          id: 1,
          title: 'قسمت ۱ — روح در اتاق عمل',
          duration: '۶۰ دقیقه',
          description: 'جراح روح‌زده وارد زندگی دکتری جوان می‌شود.',
          thumbnail: '/saintstream/posters/ghost-doctor.jpg',
        },
        {
          id: 2,
          title: 'قسمت ۲ — دست‌های قرضی',
          duration: '۵۸ دقیقه',
          description: 'دست‌های قرضی اولین عمل معجزه‌آسا را رقم می‌زنند.',
          thumbnail: '/saintstream/posters/ghost-doctor.jpg',
        },
        {
          id: 3,
          title: 'قسمت ۳ — تشخیص',
          duration: '۵۹ دقیقه',
          description: 'تشخیص بیماری مرموز تیم را به چالش می‌کشد.',
          thumbnail: '/saintstream/hero/ghost-doctor.jpg',
        },
        {
          id: 4,
          title: 'قسمت ۴ — رقابت',
          duration: '۵۷ دقیقه',
          description: 'رقابت بیمارستانی شدت می‌گیرد.',
          thumbnail: '/saintstream/posters/ghost-doctor.jpg',
        },
        {
          id: 5,
          title: 'قسمت ۵ — خاطره',
          duration: '۵۸ دقیقه',
          description: 'خاطره‌ای از گذشته روح فاش می‌شود.',
          thumbnail: '/saintstream/posters/ghost-doctor.jpg',
        },
        {
          id: 6,
          title: 'قسمت ۶ — بحران',
          duration: '۶۰ دقیقه',
          description: 'بحران در اتاق عمل همه را می‌ترساند.',
          thumbnail: '/saintstream/hero/ghost-doctor.jpg',
        },
        {
          id: 7,
          title: 'قسمت ۷ — پیمان',
          duration: '۵۹ دقیقه',
          description: 'پیمان میان انسان و روح محکم‌تر می‌شود.',
          thumbnail: '/saintstream/posters/ghost-doctor.jpg',
        },
        {
          id: 8,
          title: 'قسمت ۸ — افشا',
          duration: '۵۸ دقیقه',
          description: 'هویت روح کم‌کم روشن می‌شود.',
          thumbnail: '/saintstream/posters/ghost-doctor.jpg',
        },
        {
          id: 9,
          title: 'قسمت ۹ — تهدید',
          duration: '۶۰ دقیقه',
          description: 'تهدید بیرونی بیمارستان را هدف می‌گیرد.',
          thumbnail: '/saintstream/hero/ghost-doctor.jpg',
        },
        {
          id: 10,
          title: 'قسمت ۱۰ — آزمایش',
          duration: '۶۱ دقیقه',
          description: 'آزمایشی خطرناک برای جداسازی روح.',
          thumbnail: '/saintstream/posters/ghost-doctor.jpg',
        },
        {
          id: 11,
          title: 'قسمت ۱۱ — عشق',
          duration: '۵۸ دقیقه',
          description: 'احساسات پیچیده کار را سخت‌تر می‌کند.',
          thumbnail: '/saintstream/posters/ghost-doctor.jpg',
        },
        {
          id: 12,
          title: 'قسمت ۱۲ — دروغ',
          duration: '۵۹ دقیقه',
          description: 'دروغی بزرگ اعتماد را می‌شکند.',
          thumbnail: '/saintstream/hero/ghost-doctor.jpg',
        },
        {
          id: 13,
          title: 'قسمت ۱۳ — بازگشت',
          duration: '۶۰ دقیقه',
          description: 'بازگشت رقیبی از گذشته.',
          thumbnail: '/saintstream/posters/ghost-doctor.jpg',
        },
        {
          id: 14,
          title: 'قسمت ۱۴ — انتخاب',
          duration: '۶۲ دقیقه',
          description: 'انتخاب میان جان و هویت.',
          thumbnail: '/saintstream/posters/ghost-doctor.jpg',
        },
        {
          id: 15,
          title: 'قسمت ۱۵ — فداکاری',
          duration: '۶۳ دقیقه',
          description: 'فداکاری بزرگ نزدیک است.',
          thumbnail: '/saintstream/hero/ghost-doctor.jpg',
        },
        {
          id: 16,
          title: 'قسمت ۱۶ — وداع',
          duration: '۶۵ دقیقه',
          description: 'وداع نهایی روح و جراح.',
          thumbnail: '/saintstream/posters/ghost-doctor.jpg',
        },
      ],
    },
  ],
  'extraordinary-attorney-woo': [
    {
      id: 1,
      title: 'فصل ۱',
      episodes: [
        {
          id: 1,
          title: 'قسمت ۱ — وکیل فوق‌العاده',
          duration: '۷۰ دقیقه',
          description: 'ووی یونگ‌وو اولین روز کاری‌اش را آغاز می‌کند.',
          thumbnail: '/saintstream/posters/extraordinary-attorney-woo.jpg',
        },
        {
          id: 2,
          title: 'قسمت ۲ — پرونده نهنگ',
          duration: '۶۵ دقیقه',
          description: 'پرونده‌ای با تم نهنگ استعداد او را نشان می‌دهد.',
          thumbnail: '/saintstream/posters/extraordinary-attorney-woo.jpg',
        },
        {
          id: 3,
          title: 'قسمت ۳ — دوستی',
          duration: '۶۳ دقیقه',
          description: 'دوستی در دفتر وکالت شکل می‌گیرد.',
          thumbnail: '/saintstream/hero/extraordinary-attorney-woo.jpg',
        },
        {
          id: 4,
          title: 'قسمت ۴ — شهادت',
          duration: '۶۴ دقیقه',
          description: 'شهادت در دادگاه نقطه عطف می‌شود.',
          thumbnail: '/saintstream/posters/extraordinary-attorney-woo.jpg',
        },
        {
          id: 5,
          title: 'قسمت ۵ — پدر',
          duration: '۶۶ دقیقه',
          description: 'رابطه با پدر لایه‌های تازه‌ای می‌یابد.',
          thumbnail: '/saintstream/posters/extraordinary-attorney-woo.jpg',
        },
        {
          id: 6,
          title: 'قسمت ۶ — سوءتفاهم',
          duration: '۶۵ دقیقه',
          description: 'سوءتفاهمی دردناک پیش می‌آید.',
          thumbnail: '/saintstream/hero/extraordinary-attorney-woo.jpg',
        },
        {
          id: 7,
          title: 'قسمت ۷ — دفاع',
          duration: '۶۷ دقیقه',
          description: 'دفاع درخشان از موکلی بی‌دفاع.',
          thumbnail: '/saintstream/posters/extraordinary-attorney-woo.jpg',
        },
        {
          id: 8,
          title: 'قسمت ۸ — رقیب',
          duration: '۶۴ دقیقه',
          description: 'رقیب کاری فشار را بیشتر می‌کند.',
          thumbnail: '/saintstream/posters/extraordinary-attorney-woo.jpg',
        },
        {
          id: 9,
          title: 'قسمت ۹ — راز',
          duration: '۶۶ دقیقه',
          description: 'رازی از کودکی سر برمی‌آورد.',
          thumbnail: '/saintstream/hero/extraordinary-attorney-woo.jpg',
        },
        {
          id: 10,
          title: 'قسمت ۱۰ — عشق',
          duration: '۶۸ دقیقه',
          description: 'عشق آرام در میان پرونده‌ها رشد می‌کند.',
          thumbnail: '/saintstream/posters/extraordinary-attorney-woo.jpg',
        },
        {
          id: 11,
          title: 'قسمت ۱۱ — بحران رسانه‌ای',
          duration: '۶۵ دقیقه',
          description: 'بحران رسانه‌ای دفتر را تهدید می‌کند.',
          thumbnail: '/saintstream/posters/extraordinary-attorney-woo.jpg',
        },
        {
          id: 12,
          title: 'قسمت ۱۲ — همدلی',
          duration: '۶۷ دقیقه',
          description: 'همدلی سلاح اصلی وو می‌شود.',
          thumbnail: '/saintstream/hero/extraordinary-attorney-woo.jpg',
        },
        {
          id: 13,
          title: 'قسمت ۱۳ — دادگاه بزرگ',
          duration: '۷۰ دقیقه',
          description: 'پرونده بزرگ همه را محک می‌زند.',
          thumbnail: '/saintstream/posters/extraordinary-attorney-woo.jpg',
        },
        {
          id: 14,
          title: 'قسمت ۱۴ — انتخاب سخت',
          duration: '۶۸ دقیقه',
          description: 'انتخابی سخت میان منطق و احساس.',
          thumbnail: '/saintstream/posters/extraordinary-attorney-woo.jpg',
        },
        {
          id: 15,
          title: 'قسمت ۱۵ — حقیقت',
          duration: '۶۹ دقیقه',
          description: 'حقیقت پرونده نهایی روشن می‌شود.',
          thumbnail: '/saintstream/hero/extraordinary-attorney-woo.jpg',
        },
        {
          id: 16,
          title: 'قسمت ۱۶ — فردا',
          duration: '۷۲ دقیقه',
          description: 'فردایی تازه برای وکیل فوق‌العاده.',
          thumbnail: '/saintstream/posters/extraordinary-attorney-woo.jpg',
        },
      ],
    },
  ],
}
